import { CourseModule } from "@/lib/schema";
import {
  fillBlank,
  moduleMeta,
  multipleChoice,
  singleChoice,
  trueFalse,
} from "@/content/helpers";

export const module02: CourseModule = {
  ...moduleMeta({
    slug: "02-windows",
    order: 2,
    title: "Windows",
    subtitle: "把系统用成自己的主场",
    description: "从桌面、文件、快捷键到安装软件与系统设置，掌握 Windows 的高效使用方式。",
    icon: "Window",
    accent: "from-blue-500 to-indigo-400",
    difficulty: "入门",
    estimatedMinutes: 300,
  }),
  lessons: [
    {
      slug: "windows-ui",
      title: "Windows 界面",
      subtitle: "桌面、任务栏、开始菜单",
      durationMinutes: 25,
      difficulty: "入门",
      goals: ["认识桌面、任务栏和开始菜单", "学会窗口的基本操作", "理解通知中心与系统托盘"],
      content: [
        {
          type: "paragraph",
          text: "Windows 的界面以「桌面」为中心：桌面放快捷方式，底部任务栏固定常用应用，左下角开始菜单是打开程序的入口。整体设计鼓励鼠标和键盘配合使用。",
        },
        { type: "heading", text: "界面三件套" },
        {
          type: "list",
          items: [
            "桌面：放文件和快捷方式，右键可以新建、排序、个性化。",
            "任务栏：固定/切换程序，右侧是系统托盘（音量、网络、电池、通知）。",
            "开始菜单：搜索框 + 应用列表 + 电源按钮，是 Windows 的中枢。",
          ],
        },
        {
          type: "card",
          title: "窗口操作",
          text: "拖标题栏移动窗口，拖边缘缩放；Win+↑ 最大化、Win+←/→ 分屏，拖动窗口到屏幕边缘也能触发分屏。",
          icon: "PanelsTopLeft",
        },
        {
          type: "analogy",
          title: "办公桌类比",
          text: "桌面是桌板，任务栏是常在手边的工具架，开始菜单是抽屉里的应用仓库，通知中心是信箱。把工具放对位置，工作效率自然提升。",
        },
        {
          type: "simulator",
          kind: "windows-desktop",
          title: "模拟 Windows 桌面",
          description: "点击开始菜单、任务栏、右键菜单，体验真实的交互逻辑。",
        },
      ],
      summary: [
        "桌面、任务栏、开始菜单是 Windows 的三大入口。",
        "窗口支持拖动、缩放、最大化和分屏。",
        "系统托盘显示网络、音量、电池和通知。",
      ],
      mistakes: [
        "把所有文件都堆在桌面上，导致开机慢、找文件难。",
        "任务栏图标太多，反而找不到常用程序。",
        "不知道 Win 键的作用，错过大量快捷键。",
      ],
      thinking: ["为什么 Windows 保留桌面这个概念？", "任务栏固定应用和桌面快捷方式有什么区别？"],
      exercises: [
        { prompt: "把两个窗口分别放在屏幕左右两侧，练习 Win+← 和 Win+→。" },
        { prompt: "在开始菜单搜索栏输入「控制面板」并打开它。" },
      ],
      quiz: [
        singleChoice("q1", "Windows 的中枢入口是？", ["回收站", "开始菜单", "桌面壁纸", "系统托盘"], 1, "开始菜单包含搜索、应用列表和电源。"),
        singleChoice("q2", "最大化当前窗口的快捷键是？", ["Win+D", "Win+↑", "Alt+F4", "Ctrl+W"], 1, "Win+↑ 最大化，Win+D 显示桌面。"),
        trueFalse("q3", "任务栏只能固定程序，不能显示通知。", false, "任务栏右侧系统托盘会显示通知和状态图标。"),
        multipleChoice("q4", "桌面右键菜单可以做什么？", ["新建文件夹", "更改显示设置", "个性化壁纸", "删除 C 盘系统文件"], [0, 1, 2], "桌面右键可新建、显示设置、个性化；不会提供删除系统文件的选项。"),
        fillBlank("q5", "Windows 键通常位于键盘左下角，常被简称为____键。", "Win", "Win 键是 Windows 快捷键组合的核心。"),
      ],
      tags: ["Windows", "桌面", "入门"],
    },
    {
      slug: "files",
      title: "文件：一切资料的载体",
      subtitle: "文件名、扩展名与类型",
      durationMinutes: 25,
      difficulty: "入门",
      prerequisites: "Windows 界面",
      goals: ["理解文件与扩展名", "认识常见文件格式", "学会查看和更改默认打开方式"],
      content: [
        {
          type: "paragraph",
          text: "文件是存储在磁盘上的数据单元，可以是一篇文档、一张照片、一段视频或一个程序。文件名由「名称.扩展名」组成，扩展名（如 .docx、.jpg）告诉 Windows 用什么程序打开。",
        },
        { type: "heading", text: "常见扩展名速查" },
        {
          type: "list",
          items: [
            "文档：.docx（Word）、.xlsx（Excel）、.pptx（PowerPoint）、.pdf（通用文档）、.txt（纯文本）、.md（Markdown）。",
            "图片：.jpg、.png、.webp、.gif、.svg。",
            "音视频：.mp3、.mp4、.mkv、.mov。",
            "压缩包：.zip、.rar、.7z。",
            "程序与脚本：.exe、.msi、.py、.js、.html。",
          ],
        },
        {
          type: "callout",
          variant: "warning",
          title: "显示扩展名",
          text: "在资源管理器「查看 → 显示 → 文件扩展名」打开显示扩展名。很多病毒会伪装成「图片.exe」，看到扩展名就能识破。",
        },
        {
          type: "analogy",
          title: "文件柜类比",
          text: "文件名是文件柜上的标签，扩展名是文件夹上印的「合同」「照片」分类。标签再像，分类不对就会送到错误的人手里；系统就是靠扩展名把文件送到对应程序。",
        },
        {
          type: "simulator",
          kind: "file-manager",
          title: "在文件管理器中练习",
          description: "重命名、移动、复制、删除文件，注意扩展名变化。",
        },
      ],
      summary: [
        "文件名 = 名称 + 扩展名，扩展名决定默认打开程序。",
        "常见文档、图片、音视频、压缩包扩展名要认得。",
        "开启显示扩展名，警惕双扩展名的可疑文件。",
      ],
      mistakes: [
        "重命名时不小心改掉扩展名，导致文件无法打开。",
        "看到「.exe」的图片以为是图片，双击运行了病毒。",
        "把 .pdf 改成 .docx 以为能变成 Word，扩展名只是标签。",
      ],
      thinking: ["为什么很多网站要求上传 jpg 而不是 bmp？", "扩展名可以被修改，那系统如何真正识别文件？"],
      exercises: [
        { prompt: "开启「显示文件扩展名」，找出你电脑里 10 个不同扩展名的文件。" },
        { prompt: "把一份 txt 文件复制后改扩展名为 docx，试着用 Word 打开并观察结果。" },
      ],
      quiz: [
        singleChoice("q1", "Word 文档的标准扩展名是？", [".xlsx", ".docx", ".pptx", ".pdf"], 1, "Word 文档扩展名是 .docx。"),
        singleChoice("q2", "「图片.jpg.exe」最可能是什么？", ["正常图片", "伪装成图片的可执行程序", "压缩包", "系统文件"], 1, "真正的图片只有一个 .jpg 扩展名，多出的 .exe 是执行文件。"),
        trueFalse("q3", "把文件扩展名改为 .pdf，文件内容就会变成 PDF。", false, "扩展名只是标签，不改编码格式。"),
        multipleChoice("q4", "下面哪些是文档类扩展名？", [".docx", ".xlsx", ".mp4", ".md"], [0, 1, 3], ".mp4 是视频。"),
        fillBlank("q5", "文件名的结构是「名称.____」。", "扩展名", "扩展名决定默认打开方式。"),
      ],
      tags: ["文件", "扩展名", "Windows"],
    },
    {
      slug: "folders",
      title: "文件夹与资源管理器",
      subtitle: "把文件整理成自己的体系",
      durationMinutes: 30,
      difficulty: "入门",
      prerequisites: "文件",
      goals: ["理解文件夹树状结构", "掌握资源管理器高效操作", "建立个人文件整理体系"],
      content: [
        {
          type: "paragraph",
          text: "文件夹（目录）用于组织文件，可以层层嵌套形成树状结构。资源管理器（Win+E）是浏览和管理文件的主窗口，左侧导航栏、地址栏和搜索框是三大效率工具。",
        },
        { type: "heading", text: "资源管理器效率技巧" },
        {
          type: "list",
          items: [
            "Win+E 打开资源管理器；Ctrl+L 聚焦地址栏输入路径。",
            "Ctrl+Shift+N 新建文件夹；F2 快速重命名。",
            "按住 Ctrl 点选多个文件，按住 Shift 连续选择。",
            "右键文件 → 固定到快速访问，常用文件夹一步直达。",
          ],
        },
        {
          type: "card",
          title: "推荐的文件体系",
          text: "按「用途 + 学期 + 科目」组织：比如 文档/2025 秋/高数/作业。命名建议：日期+科目+内容，如 20250806-高数-第三章笔记.docx。",
          icon: "FolderTree",
        },
        {
          type: "analogy",
          title: "图书馆类比",
          text: "文件系统像图书馆：书架（磁盘）、楼层（文件夹）、编号（命名规范）。图书馆没有编号系统就找不到书；电脑文件不整理，搜索都救不了。",
        },
        {
          type: "simulator",
          kind: "file-manager",
          title: "整理一份混乱的文件夹",
          description: "拖动文件到正确分类，体验树状管理的威力。",
        },
      ],
      summary: [
        "文件夹树状结构是文件组织的基础。",
        "资源管理器快捷键能大幅提升操作效率。",
        "按用途与日期命名的文件体系值得建立。",
      ],
      mistakes: [
        "把所有文件放桌面或下载文件夹，几个月后找不到。",
        "文件夹嵌套七八层，路径又长又乱。",
        "同名文件到处复制，改了一个版本忘了另一个。",
      ],
      thinking: ["文件夹快捷方式和文件夹本体有什么区别？", "为什么说「桌面也是文件夹」？"],
      exercises: [
        { prompt: "在文档下建立「2026 秋/课程/计算机」文件夹结构，并创建 3 个示例文件。" },
        { prompt: "把下载文件夹里的文件按类型移动到对应文件夹。" },
      ],
      quiz: [
        singleChoice("q1", "打开资源管理器的快捷键是？", ["Win+E", "Win+D", "Ctrl+E", "Alt+Tab"], 0, "Win+E 打开文件资源管理器。"),
        singleChoice("q2", "新建文件夹的快捷键是？", ["Ctrl+N", "Ctrl+Shift+N", "Ctrl+W", "F2"], 1, "Ctrl+Shift+N 新建文件夹；Ctrl+N 在浏览器新建窗口。"),
        trueFalse("q3", "文件夹里可以再放文件夹。", false, "文件夹可以嵌套任意层。"),
        multipleChoice("q4", "哪些习惯有助于文件管理？", ["按科目建文件夹", "统一命名规范", "下载目录定期清理", "所有文件放桌面"], [0, 1, 2], "桌面堆满文件是管理大忌。"),
        fillBlank("q5", "按时间顺序排列的推荐命名格式是「日期-科目-____」。", "内容", "例如 20260806-高数-笔记。"),
      ],
      tags: ["文件夹", "资源管理器", "整理"],
    },
    {
      slug: "shortcuts",
      title: "快捷键：键盘比鼠标快",
      subtitle: "复制、粘贴、切换窗口",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["掌握 Ctrl 系核心快捷键", "学会 Win 键组合", "理解 Alt+Tab 窗口切换"],
      content: [
        {
          type: "paragraph",
          text: "快捷键是用键盘直接触发命令的方式。熟练后，你的操作速度会明显超过鼠标。Windows 最核心的组合以 Ctrl 和 Win 键为前缀。",
        },
        { type: "heading", text: "必背快捷键" },
        {
          type: "list",
          items: [
            "Ctrl+C 复制、Ctrl+X 剪切、Ctrl+V 粘贴、Ctrl+Z 撤销。",
            "Ctrl+S 保存、Ctrl+A 全选、Ctrl+F 查找。",
            "Alt+Tab 切换窗口、Win+Tab 打开任务视图。",
            "Win+D 显示桌面、Win+E 资源管理器、Win+L 锁屏。",
            "Win+Shift+S 屏幕截图。",
          ],
        },
        {
          type: "callout",
          variant: "tip",
          title: "Ctrl+V 的隐藏力量",
          text: "在 Word/PPT 里，粘贴后按 Ctrl（出现粘贴选项）再按 V，可以切换「保留源格式、合并格式、只保留文本」三种粘贴方式。",
        },
        {
          type: "simulator",
          kind: "shortcuts",
          title: "快捷键训练场",
          description: "真实按下 Ctrl+C、Ctrl+V、Alt+Tab，网页会立即识别并反馈。",
        },
      ],
      summary: [
        "Ctrl+C/X/V/Z/S/A/F 是最高频的快捷键组合。",
        "Alt+Tab 与 Win+Tab 是窗口管理利器。",
        "Win 键组合覆盖系统级操作：锁屏、桌面、截图。",
      ],
      mistakes: [
        "复制后忘记再按一次粘贴就关闭了来源程序。",
        "把 Ctrl+Z（撤销）当成删除文件。",
        "以为快捷键只在特定软件生效：Ctrl+C/V 在几乎所有程序通用。",
      ],
      thinking: ["为什么复制后系统托盘没有反应也算复制成功？", "剪切和复制到粘贴时有什么区别？"],
      exercises: [
        { prompt: "在记事本里输入一段文字，练习复制、剪切、粘贴、撤销、全选、查找。" },
        { prompt: "连续打开 3 个窗口，用 Alt+Tab 切换 10 次并计时。" },
      ],
      quiz: [
        singleChoice("q1", "复制快捷键是？", ["Ctrl+V", "Ctrl+C", "Ctrl+X", "Ctrl+Z"], 1, "Ctrl+C 复制，Ctrl+V 粘贴，Ctrl+X 剪切。"),
        singleChoice("q2", "锁屏快捷键是？", ["Win+D", "Win+L", "Win+E", "Alt+F4"], 1, "Win+L 立即锁屏。"),
        trueFalse("q3", "Alt+Tab 可以在已打开窗口之间切换。", true, "Alt+Tab 是窗口切换的标准组合。"),
        multipleChoice("q4", "以下哪些是 Ctrl 系编辑快捷键？", ["Ctrl+Z 撤销", "Ctrl+S 保存", "Ctrl+F 查找", "Win+L 锁屏"], [0, 1, 2], "Win+L 是系统锁屏，不属于编辑类。"),
        fillBlank("q5", "截取屏幕局部区域的快捷键是 Win+Shift+____。", "S", "Win+Shift+S 打开截图工具。"),
      ],
      tags: ["快捷键", "效率", "Windows"],
    },
    {
      slug: "install-software",
      title: "安装软件",
      subtitle: "从官网下载到安全安装",
      durationMinutes: 30,
      difficulty: "入门",
      prerequisites: "文件",
      goals: ["识别软件官网", "理解安装向导与自定义安装", "掌握卸载和更新软件"],
      content: [
        {
          type: "paragraph",
          text: "安装软件的第一步是找到安全的下载来源：优先软件官网或微软商店。第三方下载站常捆绑推广软件、修改主页，甚至夹带病毒。",
        },
        { type: "heading", text: "安全安装五步" },
        {
          type: "list",
          items: [
            "官网下载：看清域名，如 7-zip.org 而非 7-zip 下载站。",
            "检查文件：右键属性看数字签名与发布者。",
            "安装向导：选择「自定义安装」，取消勾选捆绑软件。",
            "安装位置：默认 C 盘即可，别把软件装到桌面。",
            "安装后：到设置-应用确认，或使用「开始」菜单卸载。",
          ],
        },
        {
          type: "card",
          title: "绿色版与便携版",
          text: "免安装的便携版（Portable）可以直接运行，适合临时工具；但来源不明的便携版可能被修改，尽量少用。",
          icon: "PackageOpen",
        },
        {
          type: "analogy",
          title: "搬家类比",
          text: "安装软件像请人搬进公寓：官网是正规中介，安装向导是合同，自定义安装是逐条看条款，卸载是退租。跳过条款的「一键安装」往往住进了一堆不速之客。",
        },
        {
          type: "callout",
          variant: "warning",
          title: "安装时的高危操作",
          text: "看到「同意并安装」之前，检查有没有预勾选的浏览器主页、全家桶、广告程序。正规软件卸载入口在设置-应用或控制面板，不是直接删文件夹。",
        },
      ],
      summary: [
        "软件只从官网或微软商店下载。",
        "安装时自定义，取消捆绑；看数字签名。",
        "卸载走系统入口，不要直接删安装目录。",
      ],
      mistakes: [
        "从「高速下载」按钮满屏的下载站下软件，装了一堆全家桶。",
        "直接删除 C 盘 Program Files 里的软件文件夹，导致残留与报错。",
        "安装时一路下一步，把捆绑软件都装上了。",
      ],
      thinking: ["为什么有些软件下载站全是「高速下载」按钮？", "软件装 C 盘真的会变慢吗？"],
      exercises: [
        { prompt: "搜索并打开一款你需要的软件的官网，确认正确的下载入口。" },
        { prompt: "卸载一个不用的软件，然后在文件资源管理器确认其目录是否被清除。" },
      ],
      quiz: [
        singleChoice("q1", "最安全的软件下载来源是？", ["任意下载站", "软件官网或微软商店", "网盘分享链接", "弹窗广告"], 1, "官网和官方商店最可靠。"),
        singleChoice("q2", "安装向导中的「自定义安装」主要用于？", ["加快下载速度", "取消捆绑软件并选择安装选项", "提高电脑性能", "注册账号"], 1, "自定义安装能取消捆绑和选择组件。"),
        trueFalse("q3", "直接删除软件安装文件夹等于正确卸载。", false, "应用应在设置-应用中卸载，避免残留。"),
        multipleChoice("q4", "安装软件前应检查哪些信息？", ["发布者签名", "文件大小", "下载站评论", "是否捆绑软件"], [0, 1, 3], "评论参考价值有限，重要的是签名和来源。"),
        fillBlank("q5", "Windows 的应用卸载入口是「设置 → ____」。", "应用", "设置-应用-已安装的应用。"),
      ],
      tags: ["软件", "安装", "安全"],
    },
    {
      slug: "zip",
      title: "压缩包",
      subtitle: "zip 与 rar 的打开和制作",
      durationMinutes: 25,
      difficulty: "入门",
      prerequisites: "文件",
      goals: ["理解压缩包的作用", "掌握解压与压缩", "知道密码压缩和常见格式"],
      content: [
        {
          type: "paragraph",
          text: "压缩包把多个文件打包并压缩，便于传输和归档。Windows 原生支持 zip：右键「压缩为 zip 文件」即可创建，双击 zip 即可查看，右键「全部解压」解压。",
        },
        { type: "heading", text: "常用格式" },
        {
          type: "list",
          items: [
            ".zip：通用性最好，Windows 原生支持。",
            ".7z：压缩率更高，需要 7-Zip 或 Bandizip。",
            ".rar：老牌格式，WinRAR 支持。",
            "密码压缩：发送敏感资料时用，密码单独通过其他渠道告知。",
          ],
        },
        {
          type: "card",
          title: "解压安全",
          text: "压缩包里可能藏有病毒：先「查看」再「解压」，对来源不明的 exe 保持警惕；解压到专门文件夹，避免文件散落一地。",
          icon: "FileArchive",
        },
        {
          type: "analogy",
          title: "行李箱类比",
          text: "压缩像把衣物抽真空装进箱子：体积变小、数量打包；解压像打开箱子把衣服挂回衣柜，系统按原路径放好。密码压缩则是给箱子加了把锁。",
        },
        {
          type: "simulator",
          kind: "file-manager",
          title: "体验压缩与解压",
          description: "在模拟文件管理中压缩、解压并查看文件。",
        },
      ],
      summary: [
        "zip 通用，7z 压缩率高，rar 是老牌格式。",
        "Windows 原生支持 zip 的创建和解压。",
        "压缩包也要防病毒，先查看再解压。",
      ],
      mistakes: [
        "解压时选择了「解压到当前文件夹」，文件散落各处。",
        "把压缩包当文件夹直接用：修改内容前必须先解压。",
        "给压缩包设置密码后忘记密码，数据无法恢复。",
      ],
      thinking: ["为什么文本压缩率高、图片视频压缩率低？", "zip 和 7z 的压缩原理有什么不同？"],
      exercises: [
        { prompt: "创建一个包含 3 个文本文件的文件夹，压缩成 zip，再解压到新目录。" },
        { prompt: "比较同一文件夹 zip 与 7z 的压缩后大小（安装 7-Zip 后）。" },
      ],
      quiz: [
        singleChoice("q1", "Windows 原生支持创建哪种压缩格式？", [".rar", ".zip", ".7z", ".tar"], 1, "Windows 原生支持 zip。"),
        singleChoice("q2", "压缩包的主要作用是？", ["提高网速", "打包文件并减小体积", "杀毒", "加密所有文件"], 1, "压缩包用于打包归档和减小体积。"),
        trueFalse("q3", "压缩过的视频文件体积会大幅缩小。", false, "视频图片通常已经是压缩格式，再压收益很小。"),
        multipleChoice("q4", "解压前应做什么？", ["查看包内文件", "检查来源", "确认是否有可执行文件", "立即删除原包"], [0, 1, 2], "先查看内容再解压，别急着删除原包。"),
        fillBlank("q5", "给压缩包设置____后，打开需要输入密码。", "密码", "密码压缩保护内容，但密码要另行安全传递。"),
      ],
      tags: ["压缩包", "zip", "文件"],
    },
    {
      slug: "drivers",
      title: "驱动",
      subtitle: "硬件与系统的翻译官",
      durationMinutes: 25,
      difficulty: "入门",
      prerequisites: "Windows 界面",
      goals: ["理解驱动的作用", "知道何时更新驱动", "会查看设备管理器"],
      content: [
        {
          type: "paragraph",
          text: "驱动（Driver）是让操作系统认识并使用硬件的小程序。没有驱动，系统不知道这块显卡能做什么、网卡怎么联网。Windows 会自动安装大部分驱动，个别硬件需要厂商工具。",
        },
        { type: "heading", text: "驱动管理要点" },
        {
          type: "list",
          items: [
            "设备管理器：Win+X → 设备管理器，查看硬件状态与驱动。",
            "Windows 更新：系统驱动的常规渠道，保持开启。",
            "显卡驱动：NVIDIA/AMD 官网或厂商工具更新，游戏/剪辑用户建议更新。",
            "驱动不是越新越好：稳定使用优先，出现异常再更新。",
          ],
        },
        {
          type: "card",
          title: "驱动异常的信号",
          text: "设备管理器出现黄色感叹号、声卡无声、显卡分辨率异常、网卡掉线，通常要先查驱动。右键设备 → 更新驱动或回退驱动。",
          icon: "Cable",
        },
        {
          type: "analogy",
          title: "翻译官类比",
          text: "硬件说自己的方言，系统说普通话，驱动就是翻译官。翻译官版本太旧、说错话，硬件和系统就会互相听不懂。",
        },
        {
          type: "callout",
          variant: "warning",
          title: "别用「驱动大师」",
          text: "第三方驱动管家类工具经常捆绑全家桶，还可能装错版本。Windows 更新和硬件官网足够解决 99% 的驱动需求。",
        },
      ],
      summary: [
        "驱动让系统认识和使用硬件。",
        "Windows 更新和厂商官网是驱动的主要来源。",
        "设备管理器是诊断驱动问题的第一站。",
      ],
      mistakes: [
        "用第三方驱动精灵批量更新，装了一堆捆绑软件。",
        "显卡频繁更新驱动，游戏反而闪退。",
        "设备正常就不管 Windows 更新，错过安全补丁。",
      ],
      thinking: ["为什么 Linux 不需要像 Windows 那样装显卡驱动？", "驱动更新日志里的「Game Ready」是什么意思？"],
      exercises: [
        { prompt: "打开设备管理器，找出 3 个设备的驱动版本。" },
        { prompt: "检查你的显卡驱动版本，去官网对比是否有重要更新。" },
      ],
      quiz: [
        singleChoice("q1", "驱动的作用是？", ["让系统使用硬件", "加速网络", "压缩文件", "清理垃圾"], 0, "驱动是系统与硬件之间的接口程序。"),
        singleChoice("q2", "查看硬件状态的工具是？", ["任务管理器", "设备管理器", "磁盘清理", "注册表编辑器"], 1, "设备管理器显示硬件和驱动状态。"),
        trueFalse("q3", "驱动越新一定越好。", false, "新驱动可能引入问题，稳定优先。"),
        multipleChoice("q4", "显卡驱动通常从哪里获取？", ["NVIDIA/AMD 官网", "Windows 更新", "手机应用商店", "硬件厂商工具"], [0, 1, 3], "手机商店不行，第三方工具不推荐。"),
        fillBlank("q5", "设备管理器中出现黄色____号表示设备异常。", "感叹", "黄色感叹号提示驱动或设备问题。"),
      ],
      tags: ["驱动", "硬件", "Windows"],
    },
    {
      slug: "system-settings",
      title: "系统设置",
      subtitle: "个性化、网络、账户与安全",
      durationMinutes: 30,
      difficulty: "入门",
      prerequisites: "Windows 界面",
      goals: ["熟悉设置应用的常用分区", "配置个性化与多显示器", "管理账户、网络与隐私"],
      content: [
        {
          type: "paragraph",
          text: "Win+I 打开设置，是 Windows 的中央控制台。系统、蓝牙和设备、网络、个性化、应用、账户、隐私和安全性是最常用的几个分区。",
        },
        { type: "heading", text: "学生必调的设置" },
        {
          type: "list",
          items: [
            "系统-电源：设置息屏与睡眠时间，兼顾省电和体验。",
            "系统-存储：开启存储感知，自动清理临时文件。",
            "个性化-主题：深色模式、壁纸、强调色。",
            "网络：连接 Wi-Fi、忘记网络、查看 IP。",
            "账户：设置 PIN 登录，比密码快且安全。",
            "隐私和安全性：按需关闭不用的应用后台权限。",
          ],
        },
        {
          type: "card",
          title: "多显示器",
          text: "外接显示器时 Win+P 选择复制或扩展；显示设置里可调整分辨率、缩放和排列方向。扩展模式适合一边看课件一边记笔记。",
          icon: "MonitorSmartphone",
        },
        {
          type: "analogy",
          title: "物业中心类比",
          text: "设置应用像小区的物业中心：换墙纸找个性化，改网络找网络和 Internet，管账户找账户，安全防护找隐私和安全性。办事找对窗口，效率翻倍。",
        },
        {
          type: "simulator",
          kind: "windows-desktop",
          title: "在模拟桌面里点开设置",
          description: "体验开始菜单到设置的路径与常用设置项。",
        },
      ],
      summary: [
        "Win+I 打开设置，分区清晰。",
        "电源、存储、主题、网络、账户、隐私是常用入口。",
        "PIN 登录、存储感知、Win+P 多屏值得立刻用起来。",
      ],
      mistakes: [
        "在控制面板和设置之间迷路：新系统优先用设置。",
        "关闭 Windows 更新或防火墙来「提速」。",
        "把显示器缩放调到 300% 还不知道怎么改回来。",
      ],
      thinking: ["为什么 Windows 还有控制面板？", "系统盘快满时，设置里哪些功能能救急？"],
      exercises: [
        { prompt: "打开设置，把系统更新和存储感知配置好。" },
        { prompt: "给账户设置一个 PIN，并测试 Win+L 锁屏后登录。" },
      ],
      quiz: [
        singleChoice("q1", "打开 Windows 设置的快捷键是？", ["Win+I", "Win+S", "Ctrl+I", "Win+P"], 0, "Win+I 打开设置。"),
        singleChoice("q2", "切换多显示器模式的快捷键是？", ["Win+Tab", "Win+P", "Win+D", "Win+E"], 1, "Win+P 选择复制/扩展等投影模式。"),
        trueFalse("q3", "PIN 登录比纯密码更安全。", false, "PIN 是绑定设备的本地凭据，比可复用的密码更抗撞库，二者并非简单强弱关系；启用 PIN 仍有 Windows Hello 保护。"),
        multipleChoice("q4", "设置中「系统」分区包含？", ["电源与睡眠", "存储感知", "显示缩放", "壁纸"], [0, 1, 2], "壁纸在个性化分区。"),
        fillBlank("q5", "Windows 的存储感知可以自动清理____文件。", "临时", "存储感知自动删除临时文件和回收站过期内容。"),
      ],
      tags: ["设置", "系统", "Windows"],
    },
    {
      slug: "disk-management",
      title: "磁盘",
      subtitle: "C 盘、D 盘与空间管理",
      durationMinutes: 30,
      difficulty: "入门",
      prerequisites: "文件夹",
      goals: ["理解分区与盘符", "学会磁盘清理", "掌握磁盘空间管理方法"],
      content: [
        {
          type: "paragraph",
          text: "一块硬盘可以分成多个分区，Windows 给每个分区一个盘符（C、D、E…）。C 盘装系统，其他盘放数据是常见习惯。磁盘管理（右键开始 → 磁盘管理）可查看分区、调整大小。",
        },
        { type: "heading", text: "空间管理三板斧" },
        {
          type: "list",
          items: [
            "磁盘清理/存储感知：清理临时文件、系统更新缓存、回收站。",
            "移动大文件：把下载、视频、游戏库迁移到 D 盘。",
            "定期检查：设置-存储查看占用，删掉重复与废弃文件。",
          ],
        },
        {
          type: "card",
          title: "C 盘为什么越来越满",
          text: "系统更新、软件缓存、微信/QQ 文件、桌面和下载目录默认都在 C 盘。把微信文件保存路径改到 D 盘，是学生最实用的减负操作。",
          icon: "HardDriveDownload",
        },
        {
          type: "analogy",
          title: "公寓类比",
          text: "C 盘是客厅（系统住这里），D 盘是卧室（数据住这里）。客厅堆满杂物，主人进出都难；把行李搬进卧室，客厅自然清爽。",
        },
        {
          type: "callout",
          variant: "warning",
          title: "危险的磁盘操作",
          text: "不要随意格式化、删除系统保留分区、压缩 C 盘到不足。调整分区前先备份重要数据；「删除卷」会清空该分区全部内容。",
        },
      ],
      summary: [
        "分区决定盘符，C 盘装系统、数据放其他盘。",
        "存储感知 + 移动大文件 + 定期检查是三板斧。",
        "磁盘管理操作有风险，先备份再动手。",
      ],
      mistakes: [
        "为了省空间把 Program Files 整个移动或删除。",
        "对 D 盘执行「格式化」前没有备份。",
        "买电脑时选「一个分区」然后长期把系统盘塞满。",
      ],
      thinking: ["为什么很多电脑出厂只有一个 C 盘？", "磁盘碎片整理对 SSD 有必要吗？"],
      exercises: [
        { prompt: "打开设置-存储，分析最大的 5 个占用项。" },
        { prompt: "把微信或 QQ 的文件保存位置改到 D 盘。" },
      ],
      quiz: [
        singleChoice("q1", "Windows 系统通常安装在哪个盘？", ["C 盘", "D 盘", "E 盘", "U 盘"], 0, "C 盘是系统分区默认盘符。"),
        singleChoice("q2", "「删除卷」会导致？", ["分区变快", "分区数据全部清空", "系统升级", "磁盘扩容"], 1, "删除卷会清空分区上的所有数据。"),
        trueFalse("q3", "SSD 需要经常碎片整理。", false, "SSD 不需要传统碎片整理，Windows 会自动执行必要的 Trim 维护。"),
        multipleChoice("q4", "哪些操作能释放 C 盘空间？", ["运行存储感知", "移动微信缓存目录", "清空回收站", "禁用 Windows Defender"], [0, 1, 2], "禁用安全组件不是释放空间的正道。"),
        fillBlank("q5", "Windows 会给每个磁盘分区分配一个字母，称为____。", "盘符", "如 C:、D:。"),
      ],
      tags: ["磁盘", "分区", "空间"],
    },
    {
      slug: "windows-10-mini",
      title: "Windows 进阶小技巧",
      subtitle: "多桌面、剪贴板、分屏与搜索",
      durationMinutes: 30,
      difficulty: "基础",
      prerequisites: "快捷键",
      goals: ["掌握多桌面与虚拟桌面", "使用云剪贴板历史", "熟练 Win 搜索与分屏布局"],
      content: [
        {
          type: "paragraph",
          text: "学会基础操作后，这几个进阶技巧能把 Windows 使用体验再提升一档：虚拟桌面、剪贴板历史、快速分屏、Win 搜索和专注模式。",
        },
        { type: "heading", text: "五个进阶技巧" },
        {
          type: "list",
          items: [
            "多桌面：Win+Tab → 新建桌面，学习一个、娱乐一个，任务栏互不干扰。",
            "剪贴板历史：Win+V 查看并粘贴最近复制过的多条内容。",
            "分屏布局：Win+Z 调出 Snap Layouts，快速排布窗口。",
            "Win 搜索：Win 键直接输入即搜即开，支持计算器和单位换算。",
            "专注助手：开启后屏蔽通知，写论文时保持专注。",
          ],
        },
        {
          type: "card",
          title: "剪贴板历史的上限",
          text: "Win+V 默认保留最近 25 条文本，可固定常用片段。注意云剪贴板会同步到微软账户，敏感内容可关闭跨设备同步。",
          icon: "ClipboardPaste",
        },
        {
          type: "analogy",
          title: "桌面分身类比",
          text: "虚拟桌面像给同一个人配了多张办公桌：写论文一张桌，查资料一张桌，娱乐一张桌。换桌不用收走眼前的东西，各自独立。",
        },
        {
          type: "simulator",
          kind: "windows-desktop",
          title: "虚拟桌面练习",
          description: "在模拟器里新建桌面并在两个桌面之间切换。",
        },
      ],
      summary: [
        "Win+Tab 新建多桌面，Win+V 打开剪贴板历史。",
        "Win+Z 分屏布局、Win 键即搜即开。",
        "专注助手按需屏蔽通知。",
      ],
      mistakes: [
        "Win+V 复制了敏感密码却同步到云端。",
        "把多个桌面当成多个账号，导致文件散落。",
        "开了专注助手忘记关闭，错过重要消息。",
      ],
      thinking: ["虚拟桌面和最小化窗口有什么本质区别？", "剪贴板历史为什么默认关闭？"],
      exercises: [
        { prompt: "创建两个虚拟桌面，把浏览器和学习软件分开，练习 Win+Ctrl+←/→ 切换。" },
        { prompt: "复制 3 段文字，用 Win+V 粘贴其中的第 2 段。" },
      ],
      quiz: [
        singleChoice("q1", "打开剪贴板历史的快捷键是？", ["Win+C", "Win+V", "Ctrl+V", "Win+H"], 1, "Win+V 显示剪贴板历史。"),
        singleChoice("q2", "新建虚拟桌面的入口是？", ["Win+Tab 任务视图", "右键桌面", "设备管理器", "控制面板"], 0, "Win+Tab 打开任务视图可新建桌面。"),
        trueFalse("q3", "剪贴板历史只能保存文本。", true, "默认支持文本历史；图片历史在部分版本也支持。"),
        multipleChoice("q4", "Win 搜索可以直接完成哪些操作？", ["打开应用", "计算数学", "查找设置", "格式化硬盘"], [0, 1, 2], "搜索不提供格式化操作。"),
        fillBlank("q5", "Snap Layouts 的快捷键是 Win+____。", "Z", "Win+Z 调出分屏布局。"),
      ],
      tags: ["Windows", "效率", "进阶"],
    },
  ],
};
