import { CourseModule } from "@/lib/schema";
import {
  fillBlank,
  moduleMeta,
  multipleChoice,
  singleChoice,
  trueFalse,
} from "@/content/helpers";

export const module03: CourseModule = {
  ...moduleMeta({
    slug: "03-internet",
    order: 3,
    title: "互联网",
    subtitle: "搜得到、下得对、传得稳",
    description: "从浏览器、搜索到下载、账号密码与网络原理，成为互联网的聪明使用者。",
    icon: "Globe",
    accent: "from-teal-500 to-emerald-400",
    difficulty: "入门",
    estimatedMinutes: 240,
  }),
  lessons: [
    {
      slug: "browser",
      title: "浏览器",
      subtitle: "你访问互联网的窗口",
      durationMinutes: 25,
      difficulty: "入门",
      goals: ["理解浏览器与搜索引擎的区别", "掌握标签页与书签管理", "认识地址栏与 URL"],
      content: [
        {
          type: "paragraph",
          text: "浏览器（Chrome、Edge、Firefox）是访问网页的程序；搜索引擎（Bing、百度、Google）是帮你找网页的服务。常见误区是把两者当成一回事：浏览器是你的车，搜索引擎是导航。",
        },
        { type: "heading", text: "浏览器必会操作" },
        {
          type: "list",
          items: [
            "Ctrl+T 新标签页、Ctrl+W 关闭标签页、Ctrl+Tab 切换标签。",
            "Ctrl+L 聚焦地址栏，直接输入网址或搜索词。",
            "Ctrl+Shift+T 恢复刚关闭的标签页。",
            "Ctrl+D 添加书签，Ctrl+Shift+B 显示书签栏。",
            "Ctrl+H 历史记录、Ctrl+J 下载列表。",
          ],
        },
        {
          type: "card",
          title: "URL 结构",
          text: "https://www.example.com/path 中，https 是协议（加密传输），example.com 是域名，/path 是资源路径。地址栏锁图标表示连接安全。",
          icon: "Link",
        },
        {
          type: "analogy",
          title: "图书馆类比",
          text: "浏览器是借书窗口，URL 是索书号，搜索引擎是馆藏目录，书签是你夹在书里的备忘纸条。",
        },
        {
          type: "callout",
          variant: "tip",
          title: "隐私模式",
          text: "Ctrl+Shift+N（Chrome）/ Ctrl+Shift+P（Firefox）打开隐私窗口：本机不保存历史记录，但网站、ISP 仍能看到你的访问。它不是隐身斗篷。",
        },
        {
          type: "simulator",
          kind: "ai-tools",
          title: "浏览器小练习",
          description: "在模拟浏览器地址栏输入网址，观察 URL 的组成部分。",
        },
      ],
      summary: [
        "浏览器是程序，搜索引擎是服务。",
        "标签、书签、历史、下载是浏览器四大管理功能。",
        "URL 由协议、域名、路径组成，锁图标代表安全连接。",
      ],
      mistakes: [
        "在搜索框里输入完整网址，绕了远路。",
        "把网址栏当搜索框输入敏感信息（银行卡号）。",
        "下载完不点下载栏的「打开」，重新去下载站找文件。",
      ],
      thinking: ["为什么打开两个浏览器很耗内存？", "浏览器插件越装越多会有什么后果？"],
      exercises: [
        { prompt: "用 Ctrl+L 打开浏览器地址栏，分别输入一个网址和一个搜索词，观察差异。" },
        { prompt: "整理书签栏：创建「学习」「工具」「娱乐」三个文件夹并收藏常用网站。" },
      ],
      quiz: [
        singleChoice("q1", "浏览器与搜索引擎的关系是？", ["同一个东西", "程序与服务的关系", "搜索引擎包含浏览器", "完全无关"], 1, "浏览器是客户端程序，搜索引擎是查找服务。"),
        singleChoice("q2", "恢复刚关闭标签页的快捷键是？", ["Ctrl+T", "Ctrl+Shift+T", "Ctrl+W", "Ctrl+D"], 1, "Ctrl+Shift+T 恢复最近关闭的标签页。"),
        trueFalse("q3", "隐私模式下网站完全不知道你是谁。", false, "网站和网络服务商仍能看到流量信息。"),
        multipleChoice("q4", "URL 通常包含哪些部分？", ["协议", "域名", "路径", "电脑 CPU 型号"], [0, 1, 2], "URL 不含硬件信息。"),
        fillBlank("q5", "地址栏中的 https 中的 s 表示____传输。", "加密", "HTTPS 使用 TLS 加密连接。"),
      ],
      tags: ["浏览器", "URL", "入门"],
    },
    {
      slug: "search",
      title: "搜索技巧",
      subtitle: "从「搜不到」到「搜得到」",
      durationMinutes: 30,
      difficulty: "入门",
      prerequisites: "浏览器",
      goals: ["学会提炼搜索关键词", "掌握常用搜索语法", "判断搜索结果的可信度"],
      content: [
        {
          type: "paragraph",
          text: "搜索的本质是「把问题翻译成关键词」。不要把整句话丢进去，先拆出核心概念、限定条件、目标来源，再决定用哪个搜索引擎。",
        },
        { type: "heading", text: "搜索语法速查" },
        {
          type: "list",
          items: [
            "引号 \"关键词\"：精确匹配短语。",
            "site: 域名：只在指定网站内搜索，如 site:edu.cn 高数。",
            "减号 -关键词：排除内容，如 笔记本 -游戏本。",
            "filetype:pdf：限定文件类型，如 论文模板 filetype:pdf。",
            "关键词 空格 关键词：默认 AND，结果同时包含。",
          ],
        },
        {
          type: "card",
          title: "搜索公式",
          text: "场景 + 对象 + 动作 + 限制。例如「校园网 无法连接 修复」比「我上不了网怎么办」有效得多；查配置用「笔记本型号 参数 官网」。",
          icon: "SearchCheck",
        },
        {
          type: "analogy",
          title: "问路类比",
          text: "问路时说「我要去一个吃饭的地方」没人帮得了你；说「附近 500 米内 有 WiFi 的川菜馆 人均 50」马上有答案。搜索引擎也一样。",
        },
        {
          type: "callout",
          variant: "warning",
          title: "甄别信息",
          text: "优先看官方来源、教育/政府域名和标注作者日期的内容。医药、金融、系统操作类问题，别信搜索结果第一条的广告位。",
        },
      ],
      summary: [
        "把问题拆成核心关键词和限定条件再搜。",
        "引号、site:、filetype:、减号是高频语法。",
        "搜索结果按来源与日期甄别可信度。",
      ],
      mistakes: [
        "搜索词太长太口语化，返回大量无关结果。",
        "直接点结果列表的「广告」链接。",
        "用同一组词换个引擎，期望得到完全不同的答案。",
      ],
      thinking: ["为什么同一个词在不同搜索引擎结果不同？", "SEO 是如何影响你看到的内容的？"],
      exercises: [
        { prompt: "用 site:edu.cn 搜索你专业的课件或公开课。" },
        { prompt: "把「我的电脑很卡怎么办」改写成 3 组更有效的搜索词并试搜。" },
      ],
      quiz: [
        singleChoice("q1", "site:edu.cn 表示？", ["只搜教育网站", "排除教育网站", "搜索全名", "加密搜索"], 0, "site: 限定搜索域名。"),
        singleChoice("q2", "精确匹配短语应使用？", ["引号", "感叹号", "省略号", "星号"], 0, "引号强制精确匹配。"),
        trueFalse("q3", "搜索结果排第一的一定最权威。", false, "广告和 SEO 会影响排名。"),
        multipleChoice("q4", "哪些技巧能提高搜索质量？", ["拆解关键词", "加 filetype 限定", "加 site 限定", "把所有问题连成一句话"], [0, 1, 2], "整句长句通常降低质量。"),
        fillBlank("q5", "搜索时用____号排除不想要的关键词。", "减", "如 笔记本 -游戏本。"),
      ],
      tags: ["搜索", "效率", "信息"],
    },
    {
      slug: "download",
      title: "下载",
      subtitle: "从下载到打开的安全路径",
      durationMinutes: 25,
      difficulty: "入门",
      prerequisites: "浏览器",
      goals: ["识别安全下载源", "管理浏览器下载", "正确处理下载后的文件"],
      content: [
        {
          type: "paragraph",
          text: "下载是把远程文件保存到本机的过程。浏览器默认存到「下载」文件夹，Ctrl+J 打开下载列表。下载安全的核心原则：只从可信来源下载。",
        },
        { type: "heading", text: "下载后的处理流程" },
        {
          type: "list",
          items: [
            "检查文件类型：课件 pdf、软件 exe、压缩包 zip。",
            "右键查看属性：来源、大小、数字签名。",
            "先杀毒/扫描再打开（Windows Defender 通常自动扫描）。",
            "安装或解压到合适位置，别让下载文件夹变成垃圾场。",
          ],
        },
        {
          type: "card",
          title: "伪装下载的危险",
          text: "下载站的「高速下载」按钮往往下载的是下载器，不是目标软件。真正的软件包通常在页面底部或「本地下载」链接。认准官网。",
          icon: "Download",
        },
        {
          type: "analogy",
          title: "取快递类比",
          text: "下载像取快递：看清发件人（官网域名）、包裹类型（扩展名）、有没有拆封（签名）。来路不明的快递，先别急着拆。",
        },
        {
          type: "callout",
          variant: "tip",
          title: "下载管理",
          text: "设置默认下载目录、开启「下载前询问每个文件的位置」，能让你更清楚自己在下载什么；Ctrl+J 可暂停、取消、定位文件。",
        },
      ],
      summary: [
        "下载只认官网和可信来源。",
        "下载后检查扩展名、签名和大小。",
        "用 Ctrl+J 管理下载，定期清理下载文件夹。",
      ],
      mistakes: [
        "点了广告位里的「下载」按钮。",
        "下载了「xxx.exe」以为是压缩包。",
        "下载文件夹常年堆积几百个文件。",
      ],
      thinking: ["为什么同一软件官网下载可能被浏览器拦截？", "BT 下载和网页直下有什么区别？"],
      exercises: [
        { prompt: "打开浏览器下载列表（Ctrl+J），清理或归档旧的下载记录。" },
        { prompt: "从官网下载一个工具软件，记录完整下载路径。" },
      ],
      quiz: [
        singleChoice("q1", "查看浏览器下载列表的快捷键是？", ["Ctrl+D", "Ctrl+J", "Ctrl+H", "Ctrl+L"], 1, "Ctrl+J 打开下载列表。"),
        singleChoice("q2", "最安全的下载来源是？", ["软件官网", "弹窗广告", "陌生网盘", "下载器"], 0, "官网最可靠。"),
        trueFalse("q3", "下载完成后必须立即安装。", false, "可以检查文件后再安装。"),
        multipleChoice("q4", "下载前应确认哪些信息？", ["文件类型", "发布者签名", "来源域名", "文件名长度"], [0, 1, 2], "文件名长度无关紧要。"),
        fillBlank("q5", "浏览器默认把下载文件放在____文件夹。", "下载", "Download 文件夹。"),
      ],
      tags: ["下载", "安全", "文件"],
    },
    {
      slug: "accounts-passwords",
      title: "账号密码",
      subtitle: "密码管理器与两步验证",
      durationMinutes: 30,
      difficulty: "入门",
      prerequisites: "互联网基础",
      goals: ["理解弱密码风险", "学会用密码管理器", "开启两步验证"],
      content: [
        {
          type: "paragraph",
          text: "账号安全的核心是「每个网站用不同强密码 + 两步验证」。人脑记不住几十个强密码，所以现代方案是密码管理器：只记一个主密码，其余交给加密保险库。",
        },
        { type: "heading", text: "安全基线" },
        {
          type: "list",
          items: [
            "不用生日、手机号、连续数字当密码。",
            "重要账号（邮箱、微信、银行）必须单独密码。",
            "开启两步验证（2FA）：手机验证码或认证 App。",
            "识别钓鱼：官网域名不对，再像也别输密码。",
          ],
        },
        {
          type: "card",
          title: "密码管理器",
          text: "浏览器内置密码管理器、微软 Authenticator、1Password、Bitwarden 都能生成并自动填充强密码。主密码一定要设得又长又独特。",
          icon: "KeyRound",
        },
        {
          type: "analogy",
          title: "钥匙串类比",
          text: "一个密码走天下就像一串钥匙开所有门，丢一把全完蛋。密码管理器是把所有钥匙锁进保险柜，只带一把主钥匙。",
        },
        {
          type: "callout",
          variant: "warning",
          title: "验证码与 OTP",
          text: "两步验证码只用于登录本账号；任何「客服」索要验证码都是诈骗。备份恢复码要单独保存，丢了可能永久失去账号。",
        },
      ],
      summary: [
        "每个账号独立强密码 + 两步验证是安全基线。",
        "密码管理器解决「记不住」问题。",
        "任何索要验证码的行为都要警惕。",
      ],
      mistakes: [
        "所有网站用同一个密码，一个泄露全部沦陷。",
        "把密码写在桌面 txt 里，文件名还叫「密码」。",
        "收到「密码过期」邮件就点链接登录。",
      ],
      thinking: ["为什么银行验证码不能告诉任何人？", "密码管理器被攻破怎么办？"],
      exercises: [
        { prompt: "检查你的邮箱和微信是否已开启两步验证，未开启就打开。" },
        { prompt: "尝试用浏览器密码管理器生成一个强密码并保存。" },
      ],
      quiz: [
        singleChoice("q1", "下列哪个密码最安全？", ["20040315", "P@ssw0rd", "e7Q!v2$kL9mZ", "abc123"], 2, "长且随机的密码更抗暴力破解。"),
        singleChoice("q2", "两步验证的核心价值是？", ["记住密码", "即使密码泄露也需要第二因素", "加速登录", "同步通讯录"], 1, "第二因素阻止仅凭密码的入侵。"),
        trueFalse("q3", "验证码可以告诉自称客服的人。", false, "验证码是身份凭证，任何人索要都要拒绝。"),
        multipleChoice("q4", "密码管理器能做什么？", ["生成强密码", "自动填充", "加密保存密码", "自动汇款"], [0, 1, 2], "密码管理器不涉及支付操作。"),
        fillBlank("q5", "2FA 的中文全称是____验证。", "两步", "Two-Factor Authentication。"),
      ],
      tags: ["密码", "安全", "账号"],
    },
    {
      slug: "network-basics",
      title: "网络基础",
      subtitle: "局域网、Wi-Fi 与网速",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["区分宽带、路由器和 Wi-Fi", "理解 IP 地址与设备", "学会排查简单网络问题"],
      content: [
        {
          type: "paragraph",
          text: "家庭网络通常这样工作：宽带猫（光猫）把运营商信号变成网络，路由器把网络分给多台设备，设备通过网线或 Wi-Fi 接入。宽带套餐的「千兆」是到光猫的速率，实际 Wi-Fi 速度还要看路由器和距离。",
        },
        { type: "heading", text: "三个核心概念" },
        {
          type: "list",
          items: [
            "IP 地址：每台联网设备的门牌号，如 192.168.1.100。",
            "局域网 LAN：家里/宿舍内部网络；广域网 WAN：互联网。",
            "带宽 Mbps：数据通道宽度；延迟 ms：数据往返时间。",
          ],
        },
        {
          type: "card",
          title: "Wi-Fi 频段",
          text: "2.4GHz 穿墙好但容易拥挤，5GHz 速度快但穿墙弱。双频路由器会把设备分配到合适频段；老旧设备只用 2.4GHz 会拖慢部分体验。",
          icon: "Wifi",
        },
        {
          type: "analogy",
          title: "快递网络类比",
          text: "光猫是城市总站，路由器是小区分拣中心，Wi-Fi 是快递员上门，IP 地址是收件人门牌，网速是快递吞吐量，延迟是下单到收货的等待。",
        },
        {
          type: "simulator",
          kind: "windows-desktop",
          title: "网络排查练习",
          description: "模拟断网排查流程：看图标、重启光猫路由、换频段、ping 网关。",
        },
      ],
      summary: [
        "宽带到光猫，路由器分发，设备通过网线或 Wi-Fi 上网。",
        "IP 是门牌号，带宽是通道宽度，延迟是往返时间。",
        "Wi-Fi 频段选择影响速度与穿墙。",
      ],
      mistakes: [
        "把「100M 宽带」当成下载速度 100MB/s（实际约 12.5MB/s）。",
        "网慢就重启光猫，其实问题在路由器位置或频段拥挤。",
        "5GHz 信号一格就说路由器坏了：穿墙弱是物理特性。",
      ],
      thinking: ["为什么晚上 Wi-Fi 特别慢？", "IPv6 和 IPv4 有什么区别？"],
      exercises: [
        { prompt: "在路由器管理页查看当前连接的设备列表，找到你自己的设备。" },
        { prompt: "测一次网速，解释带宽和延迟两个数字。" },
      ],
      quiz: [
        singleChoice("q1", "把网络分发给多台设备的设备是？", ["光猫", "路由器", "交换机", "网卡"], 1, "路由器负责局域网内设备接入与转发。"),
        singleChoice("q2", "100Mbps 宽带的理论最大下载速度约为？", ["100MB/s", "12.5MB/s", "1GB/s", "10MB/s"], 1, "Mbps 除以 8 才是 MB/s。"),
        trueFalse("q3", "5GHz Wi-Fi 穿墙能力比 2.4GHz 强。", false, "2.4GHz 穿墙更好，5GHz 更快。"),
        multipleChoice("q4", "哪些做法能改善 Wi-Fi？", ["路由器放高处", "避开微波炉等干扰源", "使用 5GHz 频段", "把路由器塞进柜子"], [0, 1, 2], "柜子会屏蔽信号。"),
        fillBlank("q5", "家用路由器管理页常用地址之一是 192.168.____.1。", "1", "如 192.168.1.1 或 192.168.0.1。"),
      ],
      tags: ["网络", "Wi-Fi", "路由器"],
    },
    {
      slug: "dns",
      title: "DNS",
      subtitle: "互联网的电话簿",
      durationMinutes: 25,
      difficulty: "基础",
      prerequisites: "网络基础",
      goals: ["理解域名与 IP 的映射", "知道 DNS 的作用", "安全地更换公共 DNS"],
      content: [
        {
          type: "paragraph",
          text: "DNS（Domain Name System，域名系统）把好记的域名翻译成 IP 地址。你输入 www.example.com，DNS 服务器查表后告诉浏览器「去这个 IP」。没有 DNS，上网就得背一长串数字。",
        },
        { type: "heading", text: "DNS 的工作流程" },
        {
          type: "list",
          items: [
            "浏览器先查本地缓存，再问 DNS 服务器。",
            "DNS 服务器逐级查询：根服务器 → 顶级域 → 权威服务器。",
            "查询结果缓存一段时间（TTL），下次访问更快。",
            "公共 DNS：如 8.8.8.8、1.1.1.1、阿里 223.5.5.5。",
          ],
        },
        {
          type: "card",
          title: "DNS 出问题什么样",
          text: "「找不到服务器」「DNS_PROBE_FINISHED_NXDOMAIN」多与 DNS 相关。先换浏览器、重启路由器，仍不行就在网卡设置中换公共 DNS。",
          icon: "Network",
        },
        {
          type: "analogy",
          title: "通讯录类比",
          text: "DNS 像手机通讯录：你想打给「妈妈」，通讯录查到号码 138xxxx，拨号机才懂。通讯录丢了/坏了，就得问别人（公共 DNS）号码。",
        },
        {
          type: "callout",
          variant: "tip",
          title: "更换 DNS 的常识",
          text: "换公共 DNS 可能改善解析速度和防污染，但不是网速万灵药；下载速度仍取决于带宽。系统设置里改一次即可，别装「DNS 加速器」。",
        },
      ],
      summary: [
        "DNS 把域名翻译成 IP 地址。",
        "解析流程：缓存 → DNS 服务器 → 逐级查询。",
        "网络报错先排查 DNS，必要时换公共 DNS。",
      ],
      mistakes: [
        "把「网页打不开」直接归咎于网速，忽略 DNS 错误码。",
        "在路由器里乱改 DNS 导致全家断网。",
        "相信「修改 DNS 让宽带翻倍」的说法。",
      ],
      thinking: ["为什么域名比 IP 更适合人使用？", "DNS 缓存为什么会造成「改了解析不生效」？"],
      exercises: [
        { prompt: "用 ipconfig /flushdns 清空 DNS 缓存（Windows），观察效果。" },
        { prompt: "查询一个公共 DNS 地址（如 223.5.5.5），了解其服务商。" },
      ],
      quiz: [
        singleChoice("q1", "DNS 的主要作用？", ["把域名解析为 IP", "压缩网页", "加密密码", "加速硬盘"], 0, "DNS 是域名系统。"),
        singleChoice("q2", "下列哪个是公共 DNS？", ["127.0.0.1", "223.5.5.5", "192.168.1.1", "255.255.255.0"], 1, "223.5.5.5 是阿里公共 DNS。"),
        trueFalse("q3", "DNS 查询结果会被缓存。", true, "缓存让重复访问更快。"),
        multipleChoice("q4", "「找不到服务器」可能的原因？", ["DNS 解析失败", "网站服务器宕机", "本地网络断开", "CPU 太老"], [0, 1, 2], "与 CPU 无关。"),
        fillBlank("q5", "DNS 的全称是 Domain Name ____。", "System", "域名系统。"),
      ],
      tags: ["DNS", "网络", "域名"],
    },
    {
      slug: "cloud-drive",
      title: "云盘",
      subtitle: "文件同步与备份",
      durationMinutes: 25,
      difficulty: "入门",
      goals: ["理解云盘同步与备份的区别", "选择合适的云盘", "注意隐私与安全"],
      content: [
        {
          type: "paragraph",
          text: "云盘把文件存在服务商服务器上，跨设备访问。常见有网盘（百度网盘、夸克）和同步盘（OneDrive、坚果云）。理解区别：网盘适合分享和备份，同步盘适合多设备编辑。",
        },
        { type: "heading", text: "使用建议" },
        {
          type: "list",
          items: [
            "学习资料、照片上传云端，本地保留原件。",
            "毕业论文、重要证件用同步盘 + 本地 + 移动硬盘三重备份。",
            "分享链接设置有效期和密码，敏感文件加密后再传。",
            "免费容量会过期，重要文件别只放一个网盘。",
          ],
        },
        {
          type: "card",
          title: "同步 ≠ 备份",
          text: "同步盘会把删除操作也同步：本地误删，云端可能同时删除。云服务都有回收站和版本历史，但「唯一副本在云端」仍不算安全。",
          icon: "CloudUpload",
        },
        {
          type: "analogy",
          title: "储物柜类比",
          text: "网盘是储物柜：放进去、拿钥匙分享；同步盘是魔术抽屉：在家里放东西，宿舍自动出现同一份。储物柜放重要文件也要留备份钥匙。",
        },
        {
          type: "callout",
          variant: "warning",
          title: "隐私提醒",
          text: "身份证照片、合同扫描件上传前确认服务商加密策略；不要用陌生「免费无限容量」网盘存私人数据。",
        },
      ],
      summary: [
        "网盘适合分享归档，同步盘适合多设备协作。",
        "重要数据遵守多重备份原则，云盘只是其中一份。",
        "分享设密码、敏感文件加密、定期整理。",
      ],
      mistakes: [
        "把所有文件只放网盘，网盘倒闭/封号就全没了。",
        "以为同步盘删除也能自动恢复，误删后找不到历史版本。",
        "公开分享的链接包含个人隐私。",
      ],
      thinking: ["为什么说「云备份」是别人的硬盘？", "端到端加密在网盘里为什么少见？"],
      exercises: [
        { prompt: "把一份课程资料上传到云盘，设置有效期与密码分享给同学。" },
        { prompt: "规划你的三重备份方案：本地、网盘、移动硬盘分别放什么。" },
      ],
      quiz: [
        singleChoice("q1", "同步盘与网盘的核心区别是？", ["同步盘自动多端同步", "网盘不能存文件", "同步盘不需要网络", "网盘一定收费"], 0, "同步盘强调实时多端一致。"),
        singleChoice("q2", "为什么云盘不能作为唯一备份？", ["服务可能关闭", "账号可能被封", "本地文件更可靠", "以上都是"], 3, "云端唯一副本风险较高。"),
        trueFalse("q3", "同步盘上的删除操作不会同步。", false, "同步是双向的，删除也会同步。"),
        multipleChoice("q4", "分享云盘文件时应？", ["设置有效期", "设置提取码", "检查是否含隐私", "公开所有文件"], [0, 1, 2], "不要盲目公开。"),
        fillBlank("q5", "OneDrive、坚果云这类强调多端一致的称为____盘。", "同步", "同步盘。"),
      ],
      tags: ["云盘", "备份", "同步"],
    },
    {
      slug: "internet-mini",
      title: "互联网进阶：隐私与工具",
      subtitle: "插件、密码填充与信息卫生",
      durationMinutes: 30,
      difficulty: "基础",
      prerequisites: "浏览器",
      goals: ["掌握浏览器插件管理", "理解指纹与跟踪", "建立个人信息卫生习惯"],
      content: [
        {
          type: "paragraph",
          text: "互联网使用到进阶阶段，关键是管理自己的数字痕迹：插件只装可信来源、定期检查权限、理解网站的跟踪方式，并用隐私工具保护自己。",
        },
        { type: "heading", text: "隐私卫生清单" },
        {
          type: "list",
          items: [
            "浏览器插件定期清理，只保留常用可信扩展。",
            "了解 Cookie：登录态、偏好、跟踪三合一。",
            "搜索引擎和浏览记录是数字足迹的一部分。",
            "公共电脑登录后一定退出账号，不点「记住我」。",
            "双因子验证、自动填充、密码管理器配合使用。",
          ],
        },
        {
          type: "card",
          title: "指纹识别",
          text: "即使用隐私模式，浏览器字体、分辨率、时区、插件组合也能形成「指纹」识别你。完全匿名很难，但减少信息暴露能显著提升隐私。",
          icon: "Fingerprint",
        },
        {
          type: "analogy",
          title: "指纹类比",
          text: "网站靠 Cookie 认识你，靠指纹记住你：一个人戴了口罩换了衣服，指纹还在。数字世界没有完全隐身，但可以减少不必要的暴露。",
        },
        {
          type: "callout",
          variant: "tip",
          title: "值得装的基础插件",
          text: "uBlock Origin（广告拦截）、浏览器内置密码管理器或 Bitwarden、翻译扩展。权限越少越好：能不读全部网站数据的就不给。",
        },
      ],
      summary: [
        "插件要少而精，定期检查权限。",
        "Cookie 与浏览器指纹共同构成跟踪方式。",
        "公共设备退出登录、不记住密码是底线习惯。",
      ],
      mistakes: [
        "装了十几个插件，每个都给「读取全部网站数据」。",
        "用公共电脑后只关窗口不退出账号。",
        "为「加速」「去广告」装来路不明的插件。",
      ],
      thinking: ["为什么「免费」插件要读取你的浏览记录？", "GDPR 的 Cookie 弹窗为什么到处都有？"],
      exercises: [
        { prompt: "检查浏览器已装插件，删除 3 个月没用过的。" },
        { prompt: "在隐私设置中查看网站权限，关闭不必要的摄像头/位置权限。" },
      ],
      quiz: [
        singleChoice("q1", "浏览器插件权限应遵循什么原则？", ["越多越好", "最小必要", "全部允许", "只读邮件"], 1, "最小权限原则。"),
        singleChoice("q2", "Cookie 的用途不包括？", ["保持登录", "记住偏好", "网站跟踪", "代替硬盘"], 3, "Cookie 不存储大文件。"),
        trueFalse("q3", "隐私模式下网站完全无法识别设备。", false, "浏览器指纹仍可能识别设备。"),
        multipleChoice("q4", "公共电脑使用后应？", ["退出所有账号", "清除浏览数据", "不点记住我", "修改 BIOS"], [0, 1, 2], "修改 BIOS 没必要。"),
        fillBlank("q5", "浏览器字体、分辨率等组合成的唯一标识被称为浏览器____。", "指纹", "Browser fingerprint。"),
      ],
      tags: ["隐私", "插件", "安全"],
    },
  ],
};
