import { CourseModule } from "@/lib/schema";
import {
  fillBlank,
  matchQuestion,
  moduleMeta,
  orderQuestion,
  quickLesson,
  singleChoice,
  trueFalse,
} from "@/content/helpers";

export const module04: CourseModule = {
  ...moduleMeta({
    slug: "04-office",
    order: 4,
    title: "Office",
    subtitle: "文档、表格与演示的高效产出",
    description: "Word、Excel、PowerPoint 三件套的系统化入门，加上 PDF 与打印技能。",
    icon: "FileText",
    accent: "from-orange-500 to-amber-400",
    difficulty: "基础",
    estimatedMinutes: 300,
  }),
  lessons: [
    quickLesson({
      slug: "word-basics",
      title: "Word 基础",
      subtitle: "从新建文档到格式化段落",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["创建并保存 Word 文档", "掌握字体与段落设置", "理解页边距与页面布局"],
      overview:
        "Word 是大学作业和论文的主要工具。核心操作围绕「选中 → 操作」展开：先选中文字，再用开始选项卡里的字体、段落工具调整格式。文件要养成「另存为 + 自动保存」的习惯。",
      points: [
        { title: "保存的黄金习惯", text: "Ctrl+S 随手保存；重要文档用「另存为」生成版本，如 论文v1、论文v2，别让一份文件越改越乱。" },
        { title: "样式而非手动调格式", text: "用「样式」设置标题、正文、引用，目录和导航窗格会自动生成，改样式全局生效。" },
        { title: "快捷键提速", text: "Ctrl+B 加粗、Ctrl+I 斜体、Ctrl+U 下划线、Ctrl+E 居中、Ctrl+Shift+8 显示格式标记。" },
      ],
      blocks: [
        {
          type: "callout",
          variant: "tip",
          title: "自动保存怎么开",
          text: "文件 → 选项 → 保存：开启「自动保存每 1 分钟」，并把恢复信息保留时间调到 10 分钟。断电、闪退后，左侧文档恢复窗格能找回大部分内容。",
        },
        {
          type: "heading",
          text: "功能区怎么找",
        },
        {
          type: "list",
          items: [
            "开始：字体、段落、样式，90% 的日常操作在这里。",
            "插入：表格、图片、页眉页脚、分页符。",
            "布局：页边距、纸张方向、分栏。",
            "引用：目录、脚注、文献管理。",
            "审阅：拼写检查、修订模式。",
          ],
        },
        {
          type: "card",
          title: "页边距为什么重要",
          text: "布局 → 页边距。默认「普通」2.54cm/3.17cm 适合一般文档；课程论文常要求上下 2.5cm、左右 3cm。别用空格凑居中，段落工具里有「居中对齐」。",
          icon: "PanelsTopLeft",
        },
        {
          type: "mermaid",
          chart: "graph LR\n  A[新建文档] --> B[写初稿]\n  B --> C[套用样式]\n  C --> D[插入目录]\n  D --> E[检查与另存为PDF]",
          caption: "一份规范文档的产出流程",
        },
        {
          type: "simulator",
          kind: "word",
          title: "模拟 Word 排版",
          description: "试试加粗、斜体、对齐和字号，感受「选中后操作」。",
        },
      ],
      analogy: "Word 像装修房子：样式是装修方案，段落是房间布局，格式标记是施工图纸，显示出来才看得懂哪里出了问题。",
      summary: ["选中后操作是 Word 第一原则。", "样式驱动文档，目录自动生成。", "版本化保存避免灾难性修改。"],
      mistakes: [
        "手动逐段调字号导致论文格式不统一。",
        "不保存直接关窗口，几小时成果消失。",
        "粘贴网页内容带满格式，文档变得难以排版。",
        "用空格和回车代替段落对齐，页面一改就乱。",
      ],
      thinking: ["为什么论文要求用样式而不是手动加粗？", "「粘贴纯文本」在什么时候最有用？"],
      exercises: [
        "创建一个 200 字文档，用样式设置三级标题并生成目录。",
        "把一段网页文字粘贴为纯文本，再应用统一字体。",
      ],
      quiz: [
        singleChoice("q1", "保存文档的快捷键是？", ["Ctrl+S", "Ctrl+P", "Ctrl+F", "Ctrl+D"], 0, "Ctrl+S 保存。"),
        trueFalse("q2", "目录可以基于标题样式自动生成。", true, "样式是自动目录的基础。"),
        fillBlank("q3", "Word 的文档扩展名是____。", ".docx", "Word 文档扩展名。"),
        matchQuestion(
          "q4",
          "把功能区和常用操作连起来。",
          ["开始", "插入", "布局", "引用"],
          ["段落样式", "页眉页脚", "页边距", "自动目录"],
          [0, 1, 2, 3],
          "开始管段落，插入管页眉，布局管边距，引用管目录。",
        ),
      ],
      tags: ["Word", "Office", "文档"],
      simulator: "word",
    }),
    quickLesson({
      slug: "word-layout",
      title: "Word 排版",
      subtitle: "页眉页脚、分页与学术排版",
      durationMinutes: 35,
      difficulty: "基础",
      prerequisites: "Word 基础",
      goals: ["设置页眉页脚与页码", "掌握分页与分节", "完成论文基本排版"],
      overview:
        "大学论文排版的关键是「分节」：封面不编页码、正文从第 1 页开始。插入 → 分页/分节符，把文档切成独立区域，再分别设置页码格式。",
      points: [
        { title: "页眉页脚", text: "插入选项卡里设置；双击页眉区域即可编辑，不同节可设置「链接到前一节」的开关。" },
        { title: "分节符", text: "页面布局 → 分隔符 → 下一页。封面、摘要、正文各占一节，页码就能各管各的。" },
        { title: "样式一致性", text: "用「导航窗格」检查标题层级，用「查找替换」统一全角半角标点。" },
      ],
      blocks: [
        {
          type: "callout",
          variant: "warning",
          title: "分页符 ≠ 分节符",
          text: "分页符只把内容推到下一页，页码会连续；分节符创建独立「节」，页码、页眉、纸张方向都能单独设置。论文封面无页码，靠的是分节，不是分页。",
        },
        {
          type: "heading",
          text: "论文排版五步",
        },
        {
          type: "list",
          ordered: true,
          items: [
            "设置页边距与正文字体（正文小四、标题三号等，按学校要求）。",
            "在封面末尾插入「分节符-下一页」。",
            "正文节取消「链接到前一节」，重新插入页码并从 1 开始。",
            "用样式设置标题层级，插入自动目录。",
            "全文检查：目录更新、页眉格式、图表编号、引用格式。",
          ],
        },
        {
          type: "mermaid",
          chart: "graph TD\n  A[封面节] --> B[摘要节]\n  B --> C[正文节]\n  C --> D[参考文献节]\n  A -.无页码.-> A\n  B -.罗马数字.-> B\n  C -.从1开始.-> C",
          caption: "论文分节与页码规则",
        },
        {
          type: "simulator",
          kind: "word",
          title: "模拟论文排版",
          description: "练习把段落排成封面、目录、正文的结构。",
        },
      ],
      analogy: "分节像把一栋楼分成独立单元：每层（节）可以有自己的门牌（页码）和装饰（页眉），互不干扰。",
      summary: ["分节是论文页码控制的核心。", "页眉页脚双击编辑，注意链接到前一节。", "导航窗格检查文档结构。"],
      mistakes: [
        "用空格和回车制造页面对齐，页数一变全乱。",
        "封面也有页码，不符合论文要求。",
        "分页符和分节符混用，页码永远对不上。",
      ],
      thinking: ["为什么「分页符」不是「分节符」？", "目录更新后页码为什么还要再更新一次？"],
      exercises: [
        "做一个含封面、正文、参考文献的文档，封面无页码、正文从 1 开始。",
        "用样式把文档标题层级修正，让导航窗格清晰可读。",
      ],
      quiz: [
        singleChoice("q1", "控制页码独立编号的关键操作是？", ["分页符", "分节符", "换行符", "制表符"], 1, "分节符创建独立区域。"),
        trueFalse("q2", "页眉页脚可以双击直接编辑。", true, "双击页眉区域进入编辑。"),
        fillBlank("q3", "论文封面通常不显示页码，正文从____开始编号。", "1", "通过分节实现。"),
        orderQuestion(
          "q4",
          "按顺序排出论文排版流程。",
          ["设置页边距与字体", "插入分节符", "正文重新编号", "生成目录"],
          [0, 1, 2, 3],
          "先设置版面，再分节，再编号，最后目录。",
        ),
      ],
      tags: ["Word", "排版", "论文"],
      simulator: "word",
    }),
    quickLesson({
      slug: "excel-basics",
      title: "Excel 基础",
      subtitle: "单元格、工作表与基本操作",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["理解单元格引用 A1", "掌握数据输入与格式", "会排序筛选"],
      overview:
        "Excel 由工作表组成，每张表由行列网格构成，单元格地址如 B2。数据录入要「一行一条记录，一列一个字段」，这是后续统计的基础。",
      points: [
        { title: "单元格地址", text: "列字母 + 行号，如 A1。公式引用单元格后，数据变化结果自动更新。" },
        { title: "数据规范", text: "日期用统一格式，数字不加单位（单位放表头），空值用空单元格而不是空格。" },
        { title: "排序筛选", text: "选中表头 → 数据选项卡 → 排序和筛选。筛选不会删除数据，只是隐藏。" },
      ],
      blocks: [
        {
          type: "callout",
          variant: "info",
          title: "Excel 里最重要的三种数据",
          text: "文本（姓名、科目）、数值（成绩、金额）、日期。日期在 Excel 里其实是带格式的数字，所以能加减和排序；身份证号则要设成文本，否则会变成科学计数法。",
        },
        {
          type: "heading",
          text: "数据表三原则",
        },
        {
          type: "list",
          items: [
            "每列一个字段，每行一条记录，表头不重复。",
            "数字不带单位，单位放列名里，如「成绩(分)」。",
            "一张表只放一类数据，别把「成绩表」和「课表」混在一张表里。",
          ],
        },
        {
          type: "card",
          title: "筛选不是删除",
          text: "点「筛选」后，表头出现小箭头；取消勾选后行只是被隐藏，再点「清除」就全部回来。排序也一样，选中整列排序会让其他列错位，永远先选表头再全表排序。",
          icon: "Filter",
        },
        {
          type: "mermaid",
          chart: "graph LR\n  A[原始数据] --> B[清洗规范]\n  B --> C[排序筛选]\n  C --> D[公式统计]\n  D --> E[图表呈现]",
          caption: "表格处理的基本流水线",
        },
        {
          type: "simulator",
          kind: "excel",
          title: "模拟 Excel 数据表",
          description: "改成绩、用公式、练习排序与筛选。",
        },
      ],
      analogy: "Excel 像记账本：表头是科目，行是每笔账，单元格是数字。本子再漂亮，数字乱填也算不出对的总账。",
      summary: ["单元格引用是 Excel 的语言。", "数据规范比公式更重要。", "筛选排序不改变原始数据。"],
      mistakes: [
        "把日期输成文本导致无法统计。",
        "在数字单元格里写「12 元」，公式算不了。",
        "合并单元格做数据表，导致筛选排序错乱。",
      ],
      thinking: ["为什么统计表里不建议用合并单元格？", "身份证号为什么需要文本格式？"],
      exercises: [
        "建一张课程成绩表：学号、姓名、成绩，练习排序和筛选。",
        "把日期统一为 2026/8/6 格式，尝试自动填充序列。",
      ],
      quiz: [
        singleChoice("q1", "单元格 B2 表示？", ["第二列第二行", "第二行第二列", "第二页第二段", "B 盘文件"], 0, "列字母在前，行号在后。"),
        trueFalse("q2", "筛选会永久删除被隐藏的行。", false, "筛选只是隐藏。"),
        fillBlank("q3", "身份证号等长数字应设为____格式存储。", "文本", "避免科学计数法。"),
        matchQuestion(
          "q4",
          "把数据类型和正确写法连起来。",
          ["成绩 92 分", "2026年8月6日", "18位身份证号"],
          ["数值 92", "日期 2026/8/6", "文本格式"],
          [0, 1, 2],
          "成绩用数值，日期用日期格式，长数字用文本。",
        ),
      ],
      tags: ["Excel", "表格", "Office"],
      simulator: "excel",
    }),
    quickLesson({
      slug: "excel-formulas",
      title: "Excel 公式",
      subtitle: "SUM、IF、VLOOKUP 与图表",
      durationMinutes: 40,
      difficulty: "基础",
      prerequisites: "Excel 基础",
      goals: ["掌握 SUM/AVERAGE 等函数", "理解 IF 逻辑", "会做基础图表"],
      overview:
        "Excel 公式以 = 开头。最常用函数：SUM 求和、AVERAGE 平均、MAX/MIN 极值、COUNT 计数、IF 条件、VLOOKUP 查找。图表则让数据一眼看懂。",
      points: [
        { title: "SUM 与引用", text: "=SUM(B2:B10) 表示 B2 到 B10 求和。用范围引用比一个个加更可靠。" },
        { title: "IF 判断", text: "=IF(条件, 是, 否)，如 =IF(F2>=60,\"及格\",\"不及格\")。注意文本要加引号。" },
        { title: "图表", text: "选中数据 → 插入图表。饼图看占比、柱状图看对比、折线图看趋势。" },
      ],
      blocks: [
        {
          type: "code",
          language: "excel",
          code: `=SUM(B2:B10)              // 求和
=AVERAGE(B2:B10)         // 平均
=MAX(B2:B10)             // 最大值
=IF(B2>=60,"及格","不及格")
=COUNTIF(B2:B10,">=60")  // 条件计数`,
          caption: "最高频的 5 个函数写法",
        },
        {
          type: "callout",
          variant: "warning",
          title: "公式最常见的三个坑",
          text: "忘记写 = 号，公式被当成文本；中文引号和英文引号混用导致报错；VLOOKUP 的查找列必须排在数据区域最左侧。",
        },
        {
          type: "card",
          title: "VLOOKUP 一句话",
          text: "=VLOOKUP(找谁, 在哪找, 返回第几列, 0)。第四个参数写 0 是精确匹配，日常几乎都用 0。",
          icon: "Search",
        },
        {
          type: "mermaid",
          chart: "graph LR\n  A[原始数据] --> B[公式计算]\n  B --> C{展示方式}\n  C -->|趋势| D[折线图]\n  C -->|对比| E[柱状图]\n  C -->|占比| F[饼图]",
          caption: "数据 → 函数 → 图表的选择",
        },
        {
          type: "simulator",
          kind: "excel",
          title: "模拟 Excel 公式",
          description: "输入 =SUM、=AVERAGE、=MAX、=MIN、=COUNT 看看结果。",
        },
      ],
      analogy: "公式像菜谱：= 是开始做饭，函数是步骤，单元格是食材。食材（数据）不好，菜谱再神也白搭。",
      summary: ["公式以 = 开头，善用范围引用。", "IF 是最常用的逻辑函数。", "图表选型看数据类型与目的。"],
      mistakes: [
        "忘记 = 号把公式当文本输入。",
        "VLOOKUP 查找列不在最左，结果错误。",
        "图表用了不合适的类型，误导结论。",
      ],
      thinking: ["VLOOKUP 和 XLOOKUP 有什么区别？", "为什么公式里的文本要用引号？"],
      exercises: [
        "为成绩表加一列及格判断（IF 函数），并统计及格人数。",
        "用 SUM 与柱状图展示一个月支出。",
      ],
      quiz: [
        singleChoice("q1", "Excel 公式必须以什么开头？", ["=", "+", "#", "@"], 0, "公式以 = 开头。"),
        singleChoice("q2", "看趋势最合适的图表是？", ["饼图", "折线图", "雷达图", "树状图"], 1, "折线图展示趋势。"),
        trueFalse("q3", "IF 函数可以嵌套使用。", true, "IF 可以嵌套多层。"),
        fillBlank("q4", "VLOOKUP 精确匹配的第四个参数应写____。", "0", "0 表示精确匹配。"),
      ],
      tags: ["Excel", "公式", "函数"],
      simulator: "excel",
    }),
    quickLesson({
      slug: "ppt-basics",
      title: "PowerPoint 基础",
      subtitle: "母版、版式与页面结构",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["理解幻灯片与版式", "使用母版统一风格", "掌握放映与导出"],
      overview:
        "PowerPoint 的核心不是动画，而是「信息结构」：每页一个观点。用「视图 → 幻灯片母版」统一字体和 Logo，比逐页修改高效百倍。",
      points: [
        { title: "母版与版式", text: "母版是模板的模板。改母版里的标题样式，所有页面同步变化；不同版式适配封面、目录、正文。" },
        { title: "信息密度", text: "每页只讲一件事，文字越少越好，要点用短语不用长句，听众看的是你讲的内容。" },
        { title: "放映与导出", text: "F5 从头放映，Shift+F5 从当前页放映；文件 → 导出可生成 PDF 或打包视频。" },
      ],
      blocks: [
        {
          type: "callout",
          variant: "tip",
          title: "母版到底改什么",
          text: "打开母版后，改这三处就够了：标题字体与颜色、正文占位符、页面角落的页码/Logo。回到普通视图，所有页面自动跟着变。",
        },
        {
          type: "heading",
          text: "一页幻灯片的信息结构",
        },
        {
          type: "list",
          items: [
            "标题：10 个字以内，说明这一页讲什么。",
            "要点：3-5 条短语，不是完整句子。",
            "图示：能上图就不上表，能上表就不上文字。",
            "来源/备注：细节放进备注栏，正文保持干净。",
          ],
        },
        {
          type: "mermaid",
          chart: "graph LR\n  A[定主题] --> B[列大纲]\n  B --> C[选母版]\n  C --> D[填每页要点]\n  D --> E[加图与数据]\n  E --> F[试讲排练]",
          caption: "PPT 制作流程",
        },
        {
          type: "simulator",
          kind: "powerpoint",
          title: "模拟幻灯片排序",
          description: "选中页面拖到正确顺序，体验演示结构。",
        },
      ],
      analogy: "PPT 像一本书：母版是统一版式设计，每页是一页书，演讲是你翻书讲给读者听。书排版统一，读起来才舒服。",
      summary: ["一页一个观点是 PPT 第一原则。", "母版统一风格，别逐页手改。", "放映快捷键 F5 / Shift+F5。"],
      mistakes: [
        "每页塞满文字，听众根本读不完。",
        "逐页改字号，母版形同虚设。",
        "动画过多，演示节奏被打断。",
      ],
      thinking: ["为什么 TED 演讲幻灯片文字那么少？", "母版和版式的关系是什么？"],
      exercises: [
        "用母版统一一套 6 页课件的标题字体与配色。",
        "把一页 200 字内容压缩成 5 个要点。",
      ],
      quiz: [
        singleChoice("q1", "从头放映的快捷键是？", ["F5", "F1", "F2", "F8"], 0, "F5 从头放映。"),
        trueFalse("q2", "母版修改会影响所有使用该版式的页面。", true, "母版是全局模板。"),
        fillBlank("q3", "PPT 演示文稿的扩展名是____。", ".pptx", "PowerPoint 扩展名。"),
      ],
      tags: ["PPT", "演示", "Office"],
      simulator: "powerpoint",
    }),
    quickLesson({
      slug: "ppt-design",
      title: "演示设计",
      subtitle: "配色、留白与视觉层次",
      durationMinutes: 35,
      difficulty: "基础",
      prerequisites: "PPT 基础",
      goals: ["掌握基础配色原则", "学会留白与对齐", "设计高质量演示页"],
      overview:
        "好看的演示来自克制：一套主色、大量留白、严格对齐、图片统一风格。设计原则是「让观众 3 秒理解页面重点」。",
      points: [
        { title: "配色", text: "主色 1 个 + 辅色 1-2 个 + 中性色。用品牌色或取色器统一；一页不超过 3 种色相。" },
        { title: "对齐与留白", text: "使用参考线对齐元素；页面四周留出安全边距。留白不是浪费，是呼吸空间。" },
        { title: "图文层次", text: "标题最大、正文次之、注释最小；图片裁成统一比例，避免风格混杂。" },
      ],
      blocks: [
        {
          type: "callout",
          variant: "warning",
          title: "对比度是底线",
          text: "文字和背景的对比度不足，投影时后排完全看不清。深色文字配浅色背景最稳；亮色文字只在深色背景上使用。",
        },
        {
          type: "heading",
          text: "做一页好幻灯片的检查清单",
        },
        {
          type: "list",
          items: [
            "3 秒能说出这一页的重点吗？",
            "标题、正文、注释的层级清楚吗？",
            "页面四周有没有留出安全边距？",
            "颜色是不是不超过 3 种色相？",
            "图片有没有水印、拉伸或风格冲突？",
          ],
        },
        {
          type: "card",
          title: "字号参考",
          text: "投影环境建议：标题 28-40pt，正文 18-24pt，注释 12-14pt。字号小于 14pt 时，后排基本看不清。",
          icon: "Type",
        },
        {
          type: "simulator",
          kind: "powerpoint",
          title: "模拟演示设计",
          description: "调整页面顺序，观察结构化排版的层次。",
        },
      ],
      analogy: "设计演示像布置展台：展品少而精、灯光聚焦、走道宽敞。展台塞满货，没人看得清主角。",
      summary: ["一页一焦点，三秒可读。", "主色克制、留白充分、对齐严谨。", "图片统一比例与风格。"],
      mistakes: [
        "彩虹色模板，页面五颜六色。",
        "所有元素居中，层次全无。",
        "从网上找的图风格混乱还带水印。",
      ],
      thinking: ["为什么黑底白字适合舞台演示却不一定适合课堂？", "字体数量为什么建议不超过 2 种？"],
      exercises: [
        "选一个主题，用 2 种颜色重做一页现有课件。",
        "收集 10 页优秀演示，总结它们的留白与对齐规律。",
      ],
      quiz: [
        singleChoice("q1", "一页幻灯片建议使用多少种主色相？", ["1-3 种", "5-8 种", "越多越好", "只用黑色"], 0, "克制的配色更专业。"),
        trueFalse("q2", "留白是浪费页面空间。", false, "留白增强可读性。"),
        fillBlank("q3", "页面元素边缘对齐所使用的辅助线叫____。", "参考线", "参考线帮助对齐。"),
        trueFalse("q4", "投影时字号小于 14pt 通常没问题。", false, "后排容易看不清，建议 18pt 以上。"),
      ],
      tags: ["PPT", "设计", "配色"],
      simulator: "powerpoint",
    }),
    quickLesson({
      slug: "pdf-print",
      title: "PDF 与打印",
      subtitle: "导出、合并、签名与打印设置",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["生成与编辑 PDF", "合并拆分 PDF", "正确设置打印"],
      overview:
        "PDF 是跨设备保真的通用格式。作业和简历用「导出为 PDF」提交，避免格式错乱；打印前先预览，控制缩放和双面设置。",
      points: [
        { title: "生成 PDF", text: "Word/PPT 中文件 → 另存为 PDF，或浏览器 Ctrl+P 打印为 PDF。文字版 PDF 可搜索，扫描件是图片。" },
        { title: "合并与签名", text: "Edge/Chrome 内置 PDF 查看与填写；合并工具用 Microsoft Edge 或 Adobe 官网在线功能；电子签名先手写再抠图，或使用签名工具。" },
        { title: "打印设置", text: "Ctrl+P 预览：选择实际大小/适合页面，双面打印选「双面-长边翻转」，黑白优先省墨。" },
      ],
      blocks: [
        {
          type: "callout",
          variant: "tip",
          title: "为什么提交用 PDF",
          text: "Word 在别人电脑上可能字体错乱、分页变化；PDF 是“印刷品”，在任何设备打开都保持一致。交作业、简历、合同优先 PDF。",
        },
        {
          type: "heading",
          text: "打印前四看",
        },
        {
          type: "list",
          items: [
            "预览：第一页和最后一页有没有空白页。",
            "缩放：选「适合页面」避免表格被切边。",
            "双面：课程资料选长边翻转，节省一半纸。",
            "份数：确认份数再点打印，别一次打 10 份。",
          ],
        },
        {
          type: "mermaid",
          chart: "graph LR\n  A[Word/PPT] --> B[另存为PDF]\n  B --> C[检查排版]\n  C --> D[合并/签名]\n  D --> E[提交或打印]",
          caption: "PDF 工作流",
        },
        {
          type: "simulator",
          kind: "pdf",
          title: "模拟 PDF 表单与打印",
          description: "填写姓名专业、电子签名，并试试打印预览。",
        },
      ],
      analogy: "PDF 像印刷好的书：排版固定、人人能读、不能随便改。打印是把它复印出来，预览是复印前的检查。",
      summary: ["提交文档优先导出 PDF。", "浏览器自带查看、填写与打印为 PDF。", "打印前预览，注意缩放与双面。"],
      mistakes: [
        "把 Word 直接发别人，打开后字体错乱。",
        "打印前不预览，表格被切到下一页。",
        "扫描版 PDF 不能搜索复制，交作业前没确认。",
      ],
      thinking: ["PDF 和 Word 文件的核心区别是什么？", "为什么扫描件 OCR 后更好用？"],
      exercises: [
        "把一份 Word 作业导出 PDF，并检查排版是否正常。",
        "打印一张 A4 测试页，调整页边距与缩放。",
      ],
      quiz: [
        singleChoice("q1", "把网页保存为 PDF 的快捷键入口是？", ["Ctrl+P", "Ctrl+E", "Ctrl+F", "Ctrl+K"], 0, "Ctrl+P 打印，选择「另存为 PDF」。"),
        trueFalse("q2", "PDF 在不同设备上排版基本一致。", true, "PDF 是固定布局格式。"),
        fillBlank("q3", "把纸质文档变成可搜索文本的技术是____。", "OCR", "光学字符识别。"),
      ],
      tags: ["PDF", "打印", "文档"],
      simulator: "pdf",
    }),
    quickLesson({
      slug: "office-workflow",
      title: "Office 综合工作流",
      subtitle: "从零到一完成课程作业",
      durationMinutes: 40,
      difficulty: "基础",
      goals: ["串联三件套完成项目", "掌握文档协作技巧", "建立办公效率习惯"],
      overview:
        "真实作业很少只用一件套：Word 写报告、Excel 分析数据、PPT 汇报，可能还要 PDF 提交。学会把数据、文档、演示串成一条流水线，才是 Office 的精髓。",
      points: [
        { title: "流水线", text: "Excel 出数据 → Word 写结论 → PPT 讲重点 → PDF 提交。每个环节输出前先问：下一环需要什么？" },
        { title: "协同办公", text: "OneDrive/腾讯文档/WPS 云同步支持多人编辑；修订模式（审阅 → 修订）保留修改痕迹，适合小组作业。" },
        { title: "模板资产", text: "把常用文档、PPT 模板、Excel 表头保存为模板，重复劳动一次做完。" },
      ],
      blocks: [
        {
          type: "callout",
          variant: "info",
          title: "真实课程项目怎么拆",
          text: "例子：一份“大学生月支出分析”作业。Excel 记录两周支出并做图表；Word 写结论和图表分析；PPT 只留 5 页讲重点；最后全部导出 PDF 归档。",
        },
        {
          type: "heading",
          text: "小组协作五原则",
        },
        {
          type: "list",
          items: [
            "一个云文档，不要每人一份“最终版”。",
            "分工写进文档开头或评论区，责任清楚。",
            "使用修订模式，审阅后再合并。",
            "文件名带日期：报告-20260814-v2。",
            "提交前最后检查一遍格式与错别字。",
          ],
        },
        {
          type: "mermaid",
          chart: "graph LR\n  A[Excel数据] --> B[Word报告]\n  B --> C[PPT演示]\n  C --> D[PDF归档]\n  B -.图表引用.-> A\n  C -.结论引用.-> B",
          caption: "三件套项目流水线",
        },
        {
          type: "simulator",
          kind: "word",
          title: "模拟最终成稿",
          description: "把结论写进模拟 Word，再考虑下一步导出 PDF。",
        },
      ],
      analogy: "Office 工作流像餐厅后厨：Excel 是备菜（数据），Word 是炒菜（报告），PPT 是摆盘（汇报），PDF 是打包外送（提交）。",
      summary: ["数据 → 报告 → 演示 → 提交的流水线。", "修订模式让小组协作可追溯。", "沉淀模板，减少重复劳动。"],
      mistakes: [
        "在 Word 里手打表格数据，绕开了 Excel。",
        "PPT 直接复制整段报告文字。",
        "多人各存一版文档，版本混乱。",
      ],
      thinking: ["云协作和本地文件共享有什么本质区别？", "为什么提交前要导 PDF 而不是发原文件？"],
      exercises: [
        "选一个课程主题，完成 Excel 数据 + Word 报告 + PPT 演示的完整小项目。",
        "体验一次带修订的小组文档协作。",
      ],
      quiz: [
        singleChoice("q1", "数据统计最合适的工具是？", ["Word", "Excel", "PPT", "记事本"], 1, "Excel 处理数据。"),
        trueFalse("q2", "修订模式可以保留每个人的修改痕迹。", true, "修订记录谁改了什么。"),
        fillBlank("q3", "多人实时编辑同一文档通常需要____同步。", "云", "云同步。"),
        orderQuestion(
          "q4",
          "按正确顺序排出三件套项目流程。",
          ["Excel 统计数据", "Word 撰写报告", "PPT 制作演示", "导出 PDF 提交"],
          [0, 1, 2, 3],
          "数据先行，报告承接，演示提炼，PDF 交付。",
        ),
      ],
      tags: ["Office", "工作流", "协作"],
      simulator: "word",
    }),
  ],
};
