import { CourseModule } from "@/lib/schema";
import {
  fillBlank,
  moduleMeta,
  quickLesson,
  singleChoice,
  trueFalse,
} from "@/content/helpers";

export const module09: CourseModule = {
  ...moduleMeta({
    slug: "09-troubleshooting",
    order: 9,
    title: "故障处理",
    subtitle: "遇到问题不再慌",
    description: "黑屏、蓝屏、断网、开不了机……掌握诊断思路，先自救再送修。",
    icon: "Wrench",
    accent: "from-red-500 to-orange-400",
    difficulty: "基础",
    estimatedMinutes: 280,
    draft: true,
  }),
  lessons: [
    quickLesson({
      slug: "troubleshooting-mindset",
      title: "故障排查思路",
      subtitle: "先软件后硬件，先简单后复杂",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["建立系统化排查思维", "记录故障信息", "区分软硬件问题"],
      overview: "排查故障像侦探破案：先问「什么时候、做了什么、出现什么提示」，按「先软件后硬件、先简单后复杂」的顺序验证，每一步只改一个变量。",
      points: [
        { title: "问题五问", text: "何时开始？做了什么操作？有什么报错？是持续还是偶发？其他程序正常吗？" },
        { title: "排除法", text: "外设逐个拔插、软件逐个关闭、驱动逐个回退；改一步测一步，别一次改三个变量。" },
        { title: "记录信息", text: "截图报错、记录错误码、查看事件查看器；送修时这些信息能救命。" },
      ],
      analogy: "排查故障像医生问诊：医生不问就开药是不负责任的，用户不问就重装也是。先问诊（收集信息），再检查（测试），最后治疗（修复）。",
      summary: ["五问收集信息，先软后硬排除。", "一次只改一个变量。", "错误码和截图是送修证据。"],
      mistakes: ["问题刚出现就重装系统。", "一次同时卸载多个软件，不知道谁引起的。", "报错不截图，凭记忆描述。"],
      thinking: ["为什么「重启解决 90% 问题」？", "事件查看器里哪些日志值得看？"],
      exercises: ["遇到小问题时练习五问记录法，写成排查日志。", "打开事件查看器，找到 3 条最近的错误记录。"],
      quiz: [
        singleChoice("q1", "排查问题的第一原则是？", ["先收集信息", "先重装系统", "先拆机", "先买新电脑"], 0, "先问清发生了什么。"),
        trueFalse("q2", "一次修改多个变量能更快定位问题。", false, "一次一变量才可归因。"),
        fillBlank("q3", "Windows 的系统日志查看工具是事件____。", "查看器", "Event Viewer。"),
      ],
      tags: ["排查", "方法", "故障"],
      draft: true,
    }),
    quickLesson({
      slug: "black-screen",
      title: "黑屏",
      subtitle: "开机黑屏与使用中黑屏",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["区分黑屏类型", "执行基础修复", "知道何时送修"],
      overview: "黑屏分两类：开机进系统前黑屏（硬件/引导问题）和使用中黑屏（驱动、过热、外接屏问题）。先看电源灯、风扇、外接显示器来缩小范围。",
      points: [
        { title: "开机黑屏", text: "电源灯亮但无显示：强制关机重启；外接显示器排除屏幕故障；反复失败进高级启动 → 启动修复/安全模式。" },
        { title: "使用中黑屏", text: "先按 Win+Ctrl+Shift+B 重置显卡驱动；过热自动保护也会黑屏，摸出风口确认。" },
        { title: "硬件信号", text: "风扇不转、指示灯无反应、开机蜂鸣/报错灯，指向内存、主板、电源问题；保修内直接送修。" },
      ],
      analogy: "黑屏像停电：先看邻居（外接屏）有没有电，再看自己家电闸（电源灯），最后看是不是跳闸（驱动）。一步步排除，别一停电就换房子。",
      summary: ["开机黑屏先试安全模式与启动修复。", "使用中黑屏先重置显卡驱动。", "电源灯与风扇状态帮助判断硬件问题。"],
      mistakes: ["黑屏就反复强制关机，磁盘反而损坏。", "外接屏正常却以为笔记本屏幕坏了。", "自己拆机保修失效。"],
      thinking: ["为什么重置显卡驱动的快捷键存在？", "黑屏和蓝屏的诊断思路有什么不同？"],
      exercises: ["模拟黑屏排查：写出从观察电源灯到外接屏的 6 步流程。", "确认你的电脑保修状态与送修联系方式。"],
      quiz: [
        singleChoice("q1", "使用中黑屏先尝试？", ["Win+Ctrl+Shift+B", "格式化硬盘", "更换内存", "刷 BIOS"], 0, "重置显卡驱动。"),
        trueFalse("q2", "开机黑屏时应先观察电源灯和风扇。", true, "硬件状态是线索。"),
        fillBlank("q3", "进入 Windows 高级启动可修复开机问题，其中常用模式是____模式。", "安全", "Safe mode。"),
      ],
      tags: ["黑屏", "故障", "修复"],
      draft: true,
    }),
    quickLesson({
      slug: "blue-screen",
      title: "蓝屏",
      subtitle: "看懂 BSOD 错误码",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["理解蓝屏含义", "读取错误码", "执行修复步骤"],
      overview: "蓝屏（BSOD）是 Windows 遇到致命错误时的保护性停机。关键不是慌，而是记下错误码（如 CRITICAL_PROCESS_DIED、MEMORY_MANAGEMENT）和「停止代码」。",
      points: [
        { title: "常见错误码", text: "内存类：MEMORY_MANAGEMENT、IRQL_NOT_LESS_OR_EQUAL；驱动类：DRIVER_IRQL_NOT_LESS_OR_EQUAL；系统文件类：CRITICAL_PROCESS_DIED。" },
        { title: "修复顺序", text: "重启 → 卸载最近驱动/软件 → 运行 sfc /scannow → 检查内存（Windows 内存诊断）→ 更新系统；反复蓝屏备份数据。" },
        { title: "蓝屏转储", text: "蓝屏瞬间截图；用 WinDbg/BlueScreenView 分析 dump 文件，定位问题驱动。" },
      ],
      analogy: "蓝屏像安全气囊弹出：不是车废了，而是系统在自我保护。记录仪表盘（错误码），去维修站（查日志）才知道是轮胎（驱动）还是发动机（硬件）。",
      summary: ["蓝屏是保护性停机，记录错误码。", "修复顺序：驱动 → 系统文件 → 内存。", "dump 分析能定位元凶。"],
      mistakes: ["蓝屏一次就重装系统。", "忽视错误码，凭感觉猜。", "蓝屏后继续不备份，直到无法开机。"],
      thinking: ["为什么超频/内存不稳会蓝屏？", "sfc /scannow 到底检查什么？"],
      exercises: ["用 sfc /scannow 扫描一次系统文件。", "运行 Windows 内存诊断并重启检查。"],
      quiz: [
        singleChoice("q1", "蓝屏时的关键信息是？", ["停止代码", "开机时间", "屏幕亮度", "键盘型号"], 0, "停止代码定位问题。"),
        trueFalse("q2", "蓝屏一定是硬件坏了。", false, "驱动和系统文件也常见。"),
        fillBlank("q3", "检查系统文件完整性的命令是 sfc /____。", "scannow", "sfc /scannow。"),
      ],
      tags: ["蓝屏", "BSOD", "故障"],
      draft: true,
    }),
    quickLesson({
      slug: "no-network",
      title: "无法联网",
      subtitle: "WiFi 消失与断连排查",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["分级排查网络问题", "使用网络诊断命令", "重置网络配置"],
      overview: "断网先分层：WiFi 图标是否正常（无线开关/驱动）→ 能否连路由器（信号/密码）→ 路由器是否上外网（光猫/宽带）→ DNS/代理问题。逐层测试。",
      points: [
        { title: "图标异常", text: "WiFi 图标带红叉：检查飞行模式、无线开关、网卡驱动；设备管理器禁用再启用网卡。" },
        { title: "命令行三连", text: "ipconfig /release + /renew 重取 IP；ipconfig /flushdns 清 DNS；ping 网关与 8.8.8.8 判断断点。" },
        { title: "重置网络", text: "设置 → 网络和 Internet → 高级网络设置 → 网络重置；会删除已保存 WiFi，需重新连接。" },
      ],
      analogy: "断网排查像查水表：先看家里水龙头（网卡），再看小区水压（路由器），最后问自来水公司（宽带）。水表（ping）能告诉你是哪一段断了。",
      summary: ["按「网卡→路由→外网→DNS」分层排查。", "ipconfig 系列命令定位断点。", "网络重置是最后手段，会清除 WiFi 配置。"],
      mistakes: ["一断网就重启路由器，问题在电脑。", "改了一堆 DNS 和代理设置，越改越乱。", "忽视飞行模式和网卡禁用状态。"],
      thinking: ["ping 通 IP 但打不开网页，问题可能在哪？", "代理软件退出后为什么仍断网？"],
      exercises: ["断网时按流程执行 ipconfig 三连并记录结果。", "找到你电脑的网卡型号与驱动版本。"],
      quiz: [
        singleChoice("q1", "判断电脑到路由器是否通，ping 什么？", ["网关地址", "8.8.8.8", "localhost", "网站域名"], 0, "先 ping 网关。"),
        singleChoice("q2", "清除 DNS 缓存的命令是？", ["ipconfig /flushdns", "ipconfig /release", "sfc /scannow", "chkdsk"], 0, "flushdns 清缓存。"),
        trueFalse("q3", "网络重置会删除已保存的 WiFi 密码。", true, "需要重新连接。"),
      ],
      tags: ["网络", "WiFi", "排查"],
      draft: true,
    }),
    quickLesson({
      slug: "no-power",
      title: "无法开机",
      subtitle: "按电源键没反应",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["排查电源问题", "执行硬件基础检查", "判断送修时机"],
      overview: "按电源键没反应：先确认电源（适配器灯、电池）、再试强制重启（长按 10 秒）、外接设备全拔、内存重插（台式机）；笔记本保修内别拆后盖。",
      points: [
        { title: "电源排查", text: "适配器灯亮不亮、接口是否松动、电池电量耗尽（插电 30 分钟再开）；部分机型有复位孔。" },
        { title: "强制重启", text: "长按电源 10-15 秒强制关机后重开；拔掉所有外设（U 盘、鼠标、扩展坞）排除外设短路。" },
        { title: "台式机深查", text: "开机后主板灯/蜂鸣提示；内存和显卡重插、清灰；电源开关与跳线检查。不确定就送修。" },
      ],
      analogy: "开不了机像车打不着火：先看有没有油（电），再看是不是档位问题（外设），最后才掀引擎盖（拆机）。掀盖前先确认自己在保修期内。",
      summary: ["先电后机：适配器、电池、复位孔。", "拔外设、长按强制重启是标准动作。", "保修期内不拆机，直接送修。"],
      mistakes: ["笔记本保修期内自己拆后盖。", "反复短按电源键，没有长按强制重启。", "带电插拔内存/硬盘导致烧毁。"],
      thinking: ["为什么静电会导致开不了机？", "开机键没反应但指示灯亮，说明什么？"],
      exercises: ["找到你笔记本的复位孔和强制重启方法。", "模拟一次完整开机排查流程，写成步骤卡。"],
      quiz: [
        singleChoice("q1", "强制关机的标准操作是？", ["长按电源 10-15 秒", "拔电源线", "狂按电源键", "合上盖子"], 0, "长按强制关机。"),
        trueFalse("q2", "开机排查前应先拔掉所有外设。", true, "排除外设短路。"),
        fillBlank("q3", "笔记本电池完全耗尽时，应插电等待约____分钟再开机。", "30", "先充一会儿电。"),
      ],
      tags: ["开机", "电源", "故障"],
      draft: true,
    }),
    quickLesson({
      slug: "slow-computer",
      title: "电脑变慢",
      subtitle: "卡顿的全面体检",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["定位卡顿来源", "优化启动与资源占用", "建立维护节奏"],
      overview: "卡顿先看任务管理器四件套：CPU、内存、磁盘、网络占用。最常见的元凶：启动项多、内存不足、磁盘 100%、后台更新/扫描、流氓软件。",
      points: [
        { title: "任务管理器诊断", text: "Ctrl+Shift+Esc 打开，按 CPU/内存/磁盘排序，找出异常进程；「启动」页禁用多余项。" },
        { title: "磁盘 100%", text: "机械硬盘满载是常态，升级 SSD 是最大提速；SSD 满 90% 也会明显变慢。" },
        { title: "后台元凶", text: "Defender 全盘扫描、系统更新、云同步、杀毒软件同时跑会抢资源；错峰更新与同步。" },
      ],
      analogy: "卡顿像交通拥堵：先看哪条路堵（CPU/磁盘），再看是不是车太多（启动项），最后考虑是不是该修路（换 SSD）。",
      summary: ["任务管理器四件套定位卡顿源。", "机械硬盘换 SSD 是最大提速。", "后台扫描与更新错峰执行。"],
      mistakes: ["装「优化软件」一键优化，反而更卡。", "硬盘满 95% 不清理，抱怨电脑慢。", "同时开几十个标签和后台程序。"],
      thinking: ["为什么刚开机特别卡？", "「清内存软件」真的有用吗？"],
      exercises: ["用任务管理器找当前占用最高的 3 个进程并分析原因。", "检查你的硬盘剩余空间是否低于 15%。"],
      quiz: [
        singleChoice("q1", "打开任务管理器的快捷键是？", ["Ctrl+Shift+Esc", "Ctrl+Alt+Delete", "Win+I", "Alt+F4"], 0, "Ctrl+Shift+Esc 直接打开。"),
        trueFalse("q2", "机械硬盘卡顿时磁盘占用常显示 100%。", true, "HDD 随机读写瓶颈明显。"),
        fillBlank("q3", "机械硬盘升级为____是最大提速手段。", "SSD", "固态硬盘。"),
      ],
      tags: ["卡顿", "优化", "性能"],
      draft: true,
    }),
    quickLesson({
      slug: "software-issues",
      title: "软件故障",
      subtitle: "闪退、报错与文件打不开",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["处理软件闪退", "修复文件关联", "使用兼容模式"],
      overview: "软件闪退先看报错与日志：内存不足、缺运行库（.NET/VC++）、文件损坏、权限不足、杀毒误杀。文件打不开先检查扩展名关联与对应软件是否安装。",
      points: [
        { title: "闪退排查", text: "事件查看器应用日志找错误；重装软件；检查磁盘空间；关闭杀毒白名单排除误杀。" },
        { title: "文件打不开", text: "确认扩展名；右键 → 打开方式 → 选择应用；勾选「始终使用此应用」修复关联。" },
        { title: "兼容性", text: "老软件右键 → 属性 → 兼容性 → 以兼容模式运行；管理员权限运行；个别需要旧版运行库。" },
      ],
      analogy: "软件故障像水管堵塞：闪退是水压不足（资源），打不开是阀门接错（关联），报错是漏水点（日志）。找到堵点再修，别全屋换管。",
      summary: ["闪退看事件日志与资源。", "文件打不开查扩展名关联。", "老软件用兼容模式。"],
      mistakes: ["软件闪退就重装系统。", "误删扩展名导致文件打不开。", "改文件关联后所有文件都用错程序打开。"],
      thinking: ["为什么缺 VC++ 运行库会报错？", "「以管理员身份运行」能解决什么问题？"],
      exercises: ["把 pdf 的默认打开方式改为 Edge，再改回你的常用软件。", "查看事件查看器应用日志里的一条错误。"],
      quiz: [
        singleChoice("q1", "文件打不开首先检查？", ["扩展名与关联程序", "网速", "屏幕亮度", "键盘"], 0, "关联是第一步。"),
        trueFalse("q2", "老软件可以在兼容模式运行。", true, "兼容性设置。"),
        fillBlank("q3", "微软常用运行库包含 .NET Framework 和 ____++。", "VC", "Visual C++ Redistributable。"),
      ],
      tags: ["软件", "故障", "修复"],
      draft: true,
    }),
    quickLesson({
      slug: "data-recovery",
      title: "数据恢复",
      subtitle: "误删文件与硬盘自救",
      durationMinutes: 35,
      difficulty: "进阶",
      goals: ["理解删除与恢复原理", "使用回收站与版本历史", "避免数据恢复误区"],
      overview: "误删文件先停写！删除只是标记空间可覆盖，继续写入会覆盖数据。优先回收站、文件历史、云盘回收站；专业恢复软件在覆盖前才有效。",
      points: [
        { title: "免费三层", text: "回收站 → 文件历史/云盘版本历史 → 系统还原点。90% 的误删在这三层内解决。" },
        { title: "专业恢复", text: "Recuva、DiskGenius 等可尝试恢复未覆盖文件；SSD 的 TRIM 会让恢复成功率大幅下降，越早越好。" },
        { title: "送修恢复", text: "硬盘异响、无法识别时停止通电，交给数据恢复机构；费用高，只救重要数据。" },
      ],
      analogy: "数据恢复像橡皮擦画：删除只是用橡皮擦擦掉铅笔字，纸还在；但再写字（写入新数据）会把纸面盖住。所以先别继续写字。",
      summary: ["误删先停写，回收站/历史/还原点优先。", "SSD 因 TRIM 恢复成功率低。", "硬盘异响立即断电送修。"],
      mistakes: ["误删后继续下载大文件。", "恢复软件装到被误删的同一块盘。", "硬盘异响还反复通电尝试。"],
      thinking: ["为什么格式化后数据还能恢复？", "「安全删除」和普通删除区别是什么？"],
      exercises: ["测试从回收站恢复一个文件。", "查看 OneDrive 的文件版本历史功能。"],
      quiz: [
        singleChoice("q1", "误删文件后的第一原则是？", ["停止写入", "立刻重启", "格式化", "拔内存"], 0, "避免覆盖。"),
        singleChoice("q2", "SSD 数据恢复成功率低的原因之一是？", ["TRIM 擦除", "转速慢", "缓存小", "电压高"], 0, "TRIM 会擦除空闲块。"),
        trueFalse("q3", "硬盘发出异响应立即断电。", true, "避免磁头刮伤盘片。"),
      ],
      tags: ["数据恢复", "误删", "硬盘"],
      draft: true,
    }),
    quickLesson({
      slug: "when-to-repair",
      title: "求助与送修",
      subtitle: "自己修还是找售后",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["判断问题归属", "选择维修渠道", "准备送修资料"],
      overview: "送修前先确定保修状态：官网序列号查询；渠道优先级：品牌售后 > 官方授权维修 > 信誉第三方。送修前备份数据、记下密码、确认维修报价。",
      points: [
        { title: "保修查询", text: "序列号在机身/BIOS/系统里，官网输入可查保修期与范围；保修内硬件故障免费，人为损坏付费。" },
        { title: "维修渠道", text: "品牌售后点最稳；授权店看授权证书；路边店风险高，可能换件；贵重数据先备份再送。" },
        { title: "送修清单", text: "备份数据、退出账号、记下故障现象与触发步骤、保存购买凭证、问清报价与时限。" },
      ],
      analogy: "送修像去医院：先查医保（保修），挂对科（售后渠道），带齐病历（故障描述）。不备份就送修，等于住院前没收拾贵重物品。",
      summary: ["官网查保修，确认范围。", "品牌售后优先，问清报价。", "送修前备份、退出账号、记录故障。"],
      mistakes: ["保修内去路边店，保修失效。", "不备份直接送修，数据被清空。", "故障描述不清，维修反复返工。"],
      thinking: ["为什么品牌售后换件贵？", "「数据恢复」和「系统维修」为什么分开收费？"],
      exercises: ["查询你的电脑序列号与保修状态。", "写一份故障描述模板，包含五问信息。"],
      quiz: [
        singleChoice("q1", "送修前最重要的准备是？", ["备份数据", "删除系统", "格式化硬盘", "换电源"], 0, "数据优先。"),
        trueFalse("q2", "品牌售后一定比第三方贵但更有保障。", true, "官方渠道更规范。"),
        fillBlank("q3", "查询保修的机器唯一标识是____号。", "序列号", "Serial number。"),
      ],
      tags: ["送修", "售后", "保修"],
      draft: true,
    }),
  ],
};
