import { CourseModule } from "@/lib/schema";
import {
  fillBlank,
  moduleMeta,
  quickLesson,
  singleChoice,
  trueFalse,
} from "@/content/helpers";

export const module10: CourseModule = {
  ...moduleMeta({
    slug: "10-ai-era",
    order: 10,
    title: "AI 时代",
    subtitle: "用 AI 放大学习与生产力",
    description: "认识主流 AI 工具，掌握 Prompt 方法，把 AI 用进学习、办公与编程。",
    icon: "Sparkles",
    accent: "from-fuchsia-500 to-pink-400",
    difficulty: "基础",
    estimatedMinutes: 360,
    draft: true,
  }),
  lessons: [
    quickLesson({
      slug: "ai-basics",
      title: "AI 基础概念",
      subtitle: "大模型、提示词与幻觉",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["理解大语言模型原理", "掌握 Prompt 基本结构", "认识 AI 的边界"],
      overview: "大语言模型（LLM）通过海量文本训练学会「接话」，本质是概率预测下一个词。它不是数据库也不是搜索引擎，因此会「一本正经地胡说」（幻觉），需要验证。",
      points: [
        { title: "模型怎么工作", text: "Transformer 架构 + 海量文本训练 + 人类反馈对齐；上下文窗口决定一次能处理多少内容。" },
        { title: "Prompt 结构", text: "角色 + 任务 + 上下文 + 要求 + 输出格式。例：「你是高数助教，把泰勒展开讲给零基础学生，用买菜类比，200 字。」" },
        { title: "边界", text: "知识截止、幻觉、无真实世界感知、数学与推理不稳、隐私风险；关键任务必须人工核实。" },
      ],
      analogy: "大模型像一个读过亿万本书的对话伙伴：知识面极广，但可能记错（幻觉），也没有常识的「真实感」；让它帮忙前，你要说清楚要求和背景。",
      summary: ["LLM 是概率接话，不是检索数据库。", "好 Prompt = 角色+任务+上下文+要求。", "AI 输出要验证，敏感信息要脱敏。"],
      mistakes: ["把 AI 当搜索引擎，问完不查证。", "一句话 Prompt 期待高质量输出。", "把私人/考试内容直接发给 AI。"],
      thinking: ["为什么 AI 数学题会算错却说得头头是道？", "上下文窗口大小如何影响使用？"],
      exercises: ["用完整 Prompt 结构让 AI 解释一个概念。", "让 AI 编一个事实，再搜索验证。"],
      quiz: [
        singleChoice("q1", "大模型生成文本的本质是？", ["预测下一个词", "查数据库", "执行程序", "联网搜索"], 0, "概率生成。"),
        trueFalse("q2", "AI 的回答一定正确。", false, "可能幻觉。"),
        fillBlank("q3", "提示词的专业叫法是____。", "Prompt", "提示词。"),
      ],
      tags: ["AI", "大模型", "Prompt"],
      simulator: "prompt-coach",
      draft: true,
    }),
    quickLesson({
      slug: "chatgpt",
      title: "ChatGPT",
      subtitle: "对话、写作与插件",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["掌握 ChatGPT 基础用法", "使用对话式追问", "了解限制与替代"],
      overview: "ChatGPT 是最知名的通用 AI 助手：对话问答、写作润色、翻译、头脑风暴。OpenAI 也提供 Deep Research、语音与图像能力。国内网络环境需合规访问或使用国内替代。",
      points: [
        { title: "对话技巧", text: "把需求写具体；一次追问只改一个条件；不满意就说「再简洁一点」「换个角度」；让 AI 先列提纲再展开。" },
        { title: "写作工作流", text: "大纲 → 分节撰写 → 润色 → 校对。让 AI 扮演编辑而不是直接代写，产出的内容更可控。" },
        { title: "限制", text: "知识截止时间、上下文长度、付费墙；涉及版权与学术诚信要谨慎。" },
      ],
      analogy: "ChatGPT 像一位反应极快的实习生：让它做一件事要说清目标、步骤和验收标准；追问和反馈才能把活干好。",
      summary: ["具体提问 + 追问迭代是核心用法。", "写作先提纲后润色。", "输出必须人工审核。"],
      mistakes: ["一次问完就当最终答案。", "让 AI 写整篇作业直接交。", "把 ChatGPT 当搜索引擎。"],
      thinking: ["为什么追问能让 AI 输出质量显著提升？", "「温度」参数如何影响回答？"],
      exercises: ["用迭代追问把一段 300 字说明压缩成 80 字。", "让 AI 为你的专业拟 3 个研究选题并评价可行性。"],
      quiz: [
        singleChoice("q1", "提升 ChatGPT 输出质量的最直接方法是？", ["具体需求+追问迭代", "多开几个窗口", "换网络", "用英文提问"], 0, "明确与迭代。"),
        trueFalse("q2", "AI 生成的作业内容可以直接提交。", false, "有学术诚信风险。"),
        fillBlank("q3", "OpenAI 的深度研究功能叫____。", "Deep Research", "深度研究。"),
      ],
      tags: ["ChatGPT", "AI", "写作"],
      simulator: "prompt-coach",
      draft: true,
    }),
    quickLesson({
      slug: "claude",
      title: "Claude",
      subtitle: "长文理解与代码助手",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["了解 Claude 特色", "使用长文档分析", "对比选择 AI 工具"],
      overview: "Claude（Anthropic）以长上下文、温和对话和代码能力著称，适合一次性丢入整篇论文、课程大纲或代码文件进行分析与总结。",
      points: [
        { title: "长文档", text: "把 PDF/长文粘贴或上传，让 Claude 提取要点、生成目录、对比观点；注意隐私与版权。" },
        { title: "代码", text: "解释代码、找 bug、写测试、重构；Claude Code 可接入终端但需要开发者环境。" },
        { title: "写作风格", text: "Claude 的回复结构化强、语气自然，适合润色与长文整理。" },
      ],
      analogy: "Claude 像一位耐心的文献综述助手：给它整本参考资料，它能帮你归纳、对比、找逻辑漏洞，但结论仍要你定。",
      summary: ["Claude 长上下文适合整篇文档分析。", "代码解释与重构是强项。", "重要结论交叉验证。"],
      mistakes: ["把整本版权书上传做摘要再传播。", "让 AI 决定论文结论。", "长文档不裁剪关键部分，输出混乱。"],
      thinking: ["为什么长上下文很重要？", "AI 工具之间如何互相验证？"],
      exercises: ["把一篇课程论文摘要交给 Claude，让它提取论点与论据。", "用 Claude 解释一段你课程里的代码。"],
      quiz: [
        singleChoice("q1", "Claude 的优势之一是？", ["长上下文", "离线运行", "不联网", "免费无限制"], 0, "长上下文是特色。"),
        trueFalse("q2", "Claude 可以分析整篇长文档。", true, "长上下文支持。"),
        fillBlank("q3", "Claude 的开发公司是____。", "Anthropic", "Anthropic。"),
      ],
      tags: ["Claude", "AI", "文档"],
      draft: true,
    }),
    quickLesson({
      slug: "gemini",
      title: "Gemini",
      subtitle: "谷歌的 AI 全家桶",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["了解 Gemini 生态", "使用多模态能力", "与谷歌搜索结合"],
      overview: "Gemini 是 Google 的多模态 AI：文本、图片、视频、代码都能处理，与 Google 搜索、Workspace（Docs、Gmail）深度集成，查事实时可结合搜索结果。",
      points: [
        { title: "多模态", text: "上传图片识别图表、试卷、屏幕截图；提问「这张图的结论是什么」比纯文本高效。" },
        { title: "Workspace 集成", text: "在 Google Docs、Gmail 里直接生成草稿、总结邮件、做表格；注意授权范围。" },
        { title: "搜索结合", text: "AI Overviews 直接给摘要，仍建议点开来源核实；Gemini 的引用更透明。" },
      ],
      analogy: "Gemini 像 Google 生态里的「全能管家」：既能看（多模态）、又能查（搜索）、还能帮写（Workspace）。但管家说的每句话都要对账。",
      summary: ["Gemini 多模态强，图表图片识别方便。", "与 Workspace 集成提升办公效率。", "AI 摘要仍要核对来源。"],
      mistakes: ["上传敏感文档到云端。", "把 AI 摘要当一手资料引用。", "忽略地区可用性差异。"],
      thinking: ["为什么「带引用」的 AI 搜索更可信？", "多模态对学习场景有什么帮助？"],
      exercises: ["给 AI 上传一张课程图表，让它解释数据结论。", "对比 Gemini 与另一个 AI 对同一问题的答案。"],
      quiz: [
        singleChoice("q1", "Gemini 的特色能力是？", ["多模态处理", "只能打字", "离线运行", "只做表格"], 0, "文本图片视频都能处理。"),
        trueFalse("q2", "AI 的摘要可以直接当参考文献引用。", false, "需要核实原始来源。"),
        fillBlank("q3", "Google 的办公套件叫 Workspace，包含 Docs 和____。", "Gmail", "邮箱与文档等。"),
      ],
      tags: ["Gemini", "AI", "多模态"],
      draft: true,
    }),
    quickLesson({
      slug: "copilot",
      title: "Copilot",
      subtitle: "微软 AI 与 Windows 集成",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["使用 Windows 的 Copilot", "了解 Microsoft 365 Copilot", "把 AI 融入 Office"],
      overview: "微软 Copilot 覆盖 Windows 系统助手、Edge 浏览器和 Microsoft 365：总结网页、写邮件、生成 PPT、Excel 分析。对 Windows 用户来说是最顺手的入口之一。",
      points: [
        { title: "Windows Copilot", text: "系统级助手可问设置、文件、系统问题；部分能力需要账户与地区支持。" },
        { title: "365 Copilot", text: "在 Word 里生成草稿、PowerPoint 生成大纲、Excel 分析数据；需要订阅许可。" },
        { title: "与 Edge 集成", text: "Edge 侧栏 Copilot 可总结网页、对比价格、翻译；看长网页论文时效率高。" },
      ],
      analogy: "Copilot 像 Windows 自带的「新手引导员」：不熟悉系统时问它，写文档时它当助手；但正式提交前要检查它生成的数字和引用。",
      summary: ["Copilot 覆盖系统、浏览器与 Office。", "365 Copilot 需要订阅许可。", "生成内容需人工校对。"],
      mistakes: ["以为系统 Copilot 免费包含全部 365 功能。", "让 AI 直接算财务数据不核对。", "把公司/学校机密文档喂给 AI。"],
      thinking: ["Copilot 和 ChatGPT 的核心差异是什么？", "AI 写邮件如何避免「AI 味」？"],
      exercises: ["用 Edge 侧栏总结一篇长网页文章。", "在 Word 里用 Copilot 生成一段大纲并修改。"],
      quiz: [
        singleChoice("q1", "Microsoft 365 Copilot 可以做什么？", ["生成 PPT 大纲", "修理硬件", "更换屏幕", "加速风扇"], 0, "365 集成办公。"),
        trueFalse("q2", "Copilot 只存在于 Windows。", false, "还有 Edge、365、GitHub 等。"),
        fillBlank("q3", "Edge 浏览器侧栏的 AI 助手也叫____。", "Copilot", "Edge Copilot。"),
      ],
      tags: ["Copilot", "微软", "AI"],
      draft: true,
    }),
    quickLesson({
      slug: "perplexity",
      title: "Perplexity",
      subtitle: "带引用的 AI 搜索",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["理解 AI 搜索与传统搜索差异", "用 Perplexity 查资料", "核实引用来源"],
      overview: "Perplexity 是 AI 搜索：实时联网、回答带引用、追问可深挖。适合「快速了解一个话题 + 找到来源」，但引用可能错配，仍要点开原始链接验证。",
      points: [
        { title: "用法", text: "直接问问题，回答下方有引用编号；点引用看原文；「聚焦」可限定学术/视频/论坛。" },
        { title: "与普通搜索对比", text: "普通搜索给链接列表，AI 搜索给综合答案；适合探索型问题，不适合「必须官方原文」的场合。" },
        { title: "学术场景", text: "找课程论文资料时用它定位来源，再回原文细读；引用格式要回到原始文献。" },
      ],
      analogy: "Perplexity 像一位带书单的图书管理员：先给你结论，再递上书架号（引用）。结论可以信一半，书必须自己翻。",
      summary: ["AI 搜索回答带引用，适合快速概览。", "引用可能错配，必须回到原文。", "学术写作以一手文献为准。"],
      mistakes: ["把 AI 搜索的「引用」直接写进论文。", "不点开来源就采用结论。", "用 AI 搜索替代数据库检索。"],
      thinking: ["为什么 AI 搜索偶尔会引用不存在的页面？", "RAG 技术如何提升引用准确性？"],
      exercises: ["用 Perplexity 查一个课程概念，点开 2 个引用来源。", "把 AI 搜索和普通搜索引擎结果对比。"],
      quiz: [
        singleChoice("q1", "Perplexity 的核心特色是？", ["带引用的实时搜索", "离线聊天", "只读 PDF", "代码编译"], 0, "回答附引用。"),
        trueFalse("q2", "AI 搜索的引用一定准确。", false, "可能错配，需验证。"),
        fillBlank("q3", "让 AI 只检索学术资料可开启____模式。", "学术", "Academic/聚焦。"),
      ],
      tags: ["Perplexity", "AI 搜索", "引用"],
      draft: true,
    }),
    quickLesson({
      slug: "ai-office",
      title: "AI 办公",
      subtitle: "文档、表格、PPT 的 AI 工作流",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["用 AI 加速文档产出", "用 AI 处理表格数据", "用 AI 生成演示大纲"],
      overview: "AI 办公的核心是「半自动」：AI 生成初稿/公式/大纲，人类审核修改。文档：先大纲后填充；表格：描述需求让 AI 给公式；PPT：先大纲再排版。",
      points: [
        { title: "AI 文档", text: "让 AI 生成结构大纲、润色措辞、提炼摘要；把「写得像 AI」的句子改成自己的表达。" },
        { title: "AI 表格", text: "描述需求让 AI 生成 Excel 公式与思路；复杂数据处理用 Python/Pandas（AI 辅助写）更高效。" },
        { title: "AI PPT", text: "给 AI 主题和页数生成大纲，再手动补充数据与案例；Gamma 等工具可直接生成初稿。" },
      ],
      analogy: "AI 办公像请了个助理：助理能快速出草稿，但签字盖章、最终把关的是你。助理水平取决于你交代得多清楚。",
      summary: ["AI 产出初稿，人类负责审核。", "公式与大纲类任务 AI 效率极高。", "输出要符合自己的表达习惯。"],
      mistakes: ["AI 生成的表格公式不核对，数字错。", "整篇复制 AI 文案，一眼假。", "把内部数据直接喂给外部 AI。"],
      thinking: ["如何消除 AI 文案的「机器味」？", "哪些办公任务 AI 目前做不好？"],
      exercises: ["让 AI 为课程报告生成大纲，再手动补充 3 个数据点。", "描述一个 Excel 需求，让 AI 生成公式并验证结果。"],
      quiz: [
        singleChoice("q1", "AI 办公的正确姿势是？", ["AI 初稿+人工审核", "AI 全自动交付", "完全不用 AI", "AI 替人开会"], 0, "人机协作。"),
        trueFalse("q2", "AI 生成的 Excel 公式无需验证。", false, "必须验证结果。"),
        fillBlank("q3", "AI 生成 PPT 的工具之一是____。", "Gamma", "Gamma 等 AI 演示工具。"),
      ],
      tags: ["AI", "办公", "效率"],
      simulator: "prompt-coach",
      draft: true,
    }),
    quickLesson({
      slug: "ai-learning",
      title: "AI 学习",
      subtitle: "用 AI 当私人助教",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["用 AI 解释概念", "用 AI 出题自测", "建立 AI 学习工作流"],
      overview: "AI 是最好的私人助教之一：让它用类比解释概念、生成练习题、批改思路、制定复习计划。关键是「先自己思考再问 AI」，避免依赖。",
      points: [
        { title: "费曼式学习", text: "自己先讲一遍，卡壳处问 AI；让 AI 扮演零基础学生，你讲给它听，它提问挑错。" },
        { title: "主动回忆", text: "让 AI 出选择题/判断题自测；用「不要给答案，先提示」的指令避免直接看答案。" },
        { title: "复习计划", text: "提供课程大纲和考试时间，让 AI 生成间隔复习计划；AI 不懂你的真实掌握度，计划要自己调整。" },
      ],
      analogy: "AI 助教像健身房教练：能教动作、能陪练、能制定计划，但练不练、重量加不加，取决于你自己。",
      summary: ["先思考后问 AI，避免答案依赖。", "费曼法与自测题是 AI 学习两大利器。", "计划要结合自己的掌握度调整。"],
      mistakes: ["直接要答案抄进错题本。", "AI 说不懂的知识不查书。", "让 AI 替写读书报告交作业。"],
      thinking: ["为什么「让 AI 提问」比「让 AI 回答」更有学习价值？", "间隔复习为什么有效？"],
      exercises: ["选一个概念，用费曼法讲给 AI，让它挑出逻辑漏洞。", "让 AI 出 5 道自测题，先自己答再看解析。"],
      quiz: [
        singleChoice("q1", "用 AI 学习最有效的方式是？", ["主动回忆+自测", "直接抄答案", "让 AI 代写", "不提问只看"], 0, "主动学习。"),
        trueFalse("q2", "AI 生成的复习计划应结合个人掌握度调整。", true, "AI 不了解你。"),
        fillBlank("q3", "把知识讲给别人以检验理解的方法是____学习法。", "费曼", "Feynman technique。"),
      ],
      tags: ["AI", "学习", "助教"],
      simulator: "prompt-coach",
      draft: true,
    }),
    quickLesson({
      slug: "ai-programming",
      title: "AI 编程",
      subtitle: "从抄代码到会调代码",
      durationMinutes: 40,
      difficulty: "进阶",
      goals: ["用 AI 辅助写代码", "学会提问代码问题", "理解 AI 代码风险"],
      overview: "AI 编程工具（GitHub Copilot、Cursor、Claude）能生成代码、解释报错、写测试。但 AI 代码可能有 bug、过时 API 和安全漏洞，必须能读懂再使用。",
      points: [
        { title: "提问代码问题", text: "给足上下文：语言、框架、报错全文、预期行为、尝试过什么。「这段代码为什么报错」不如贴代码+报错。" },
        { title: "工作流", text: "让 AI 先写思路再写代码；逐函数审查；跑测试；让 AI 解释生成的每段代码。" },
        { title: "风险", text: "AI 可能编造不存在的库、用旧 API、写出 SQL 注入等漏洞；生产代码必须人工审计。" },
      ],
      analogy: "AI 编程像找代码代练：代练能通关（出代码），但你要看懂操作（读懂代码），否则副本更新（需求变化）就卡死。",
      summary: ["AI 编程是加速器，不是替代品。", "提问给足上下文，先思路后代码。", "安全漏洞与过时 API 要人工审查。"],
      mistakes: ["不读代码直接复制粘贴。", "报错信息只贴一半。", "把含密钥的代码发给 AI 审查。"],
      thinking: ["为什么「让 AI 解释代码」比「让 AI 写代码」更有学习价值？", "AI 生成的代码测试覆盖率如何保证？"],
      exercises: ["用 AI 解释一段课程代码，再复述给同学。", "让 AI 修复一个报错，解释修复原因。"],
      quiz: [
        singleChoice("q1", "向 AI 提问代码问题时应提供？", ["报错全文与上下文", "只有报错代码行", "项目密码", "服务器地址"], 0, "上下文充分。"),
        trueFalse("q2", "AI 生成的代码可以不经审查直接用。", false, "可能含漏洞。"),
        fillBlank("q3", "GitHub 的 AI 结对编程工具是____。", "Copilot", "GitHub Copilot。"),
      ],
      tags: ["AI", "编程", "Copilot"],
      simulator: "python",
      draft: true,
    }),
    quickLesson({
      slug: "ai-safety",
      title: "AI 安全与伦理",
      subtitle: "防诈骗、防依赖、守底线",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["识别 AI 诈骗", "管理 AI 依赖", "理解学术与版权红线"],
      overview: "AI 时代的新风险：AI 换脸/变声诈骗、AI 生成的假新闻、深度伪造证据；同时要防「AI 依赖症」——不思考、不记忆、不判断。",
      points: [
        { title: "AI 诈骗", text: "视频/语音「亲友」借钱先回拨验证；AI 生成的「官方通知」看域名；银行不会用 AI 打电话要验证码。" },
        { title: "依赖管理", text: "重要知识先自己学再问 AI；每天设定「无 AI 思考时间」；用 AI 检查作业而非代做。" },
        { title: "学术红线", text: "学校对 AI 使用有规定；AI 生成内容不署名提交属学术不端；引用 AI 输出要声明。" },
      ],
      analogy: "AI 像强大的工具刀：切菜省力（效率），但刀法不练（能力）不行，拿刀伤人（滥用）犯法。工具无罪，使用方式有对错。",
      summary: ["验证身份与信息源，防 AI 诈骗。", "保持独立思考，设定无 AI 时间。", "学术诚信红线不可逾越。"],
      mistakes: ["接到「亲人」视频电话就直接转账。", "大学四年用 AI 代写，毕业即失业。", "把 AI 输出当官方公告传播。"],
      thinking: ["如何向长辈解释 AI 诈骗？", "「AI 写的东西算不算你的作品」你怎么看？"],
      exercises: ["和家人约定一个「验证暗号」用于紧急求助。", "查学校对 AI 使用的规定，写下自己的 AI 使用边界。"],
      quiz: [
        singleChoice("q1", "防 AI 诈骗的第一原则是？", ["多渠道验证身份", "相信声音", "相信视频", "立即转账"], 0, "回拨验证。"),
        trueFalse("q2", "AI 生成内容直接提交作业可能构成学术不端。", true, "需遵守学校规定。"),
        fillBlank("q3", "用 AI 换脸制造虚假视频被称为____。", "Deepfake", "深度伪造。"),
      ],
      tags: ["AI", "安全", "伦理"],
      draft: true,
    }),
  ],
};
