import { CourseModule } from "@/lib/schema";
import {
  fillBlank,
  moduleMeta,
  quickLesson,
  singleChoice,
  trueFalse,
} from "@/content/helpers";

export const module11: CourseModule = {
  ...moduleMeta({
    slug: "11-programming",
    order: 11,
    title: "编程基础",
    subtitle: "写出人生第一行代码",
    description: "从程序思想到 Python、网页三件套与 Git/GitHub，迈入编程世界。",
    icon: "Code2",
    accent: "from-cyan-500 to-blue-400",
    difficulty: "进阶",
    estimatedMinutes: 420,
    draft: true,
  }),
  lessons: [
    quickLesson({
      slug: "what-is-program",
      title: "什么是程序",
      subtitle: "指令、算法与程序语言",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["理解程序本质", "认识算法", "知道编程语言如何执行"],
      overview: "程序 = 数据 + 指令 + 流程控制。算法是解决问题的步骤，编程语言是写指令的语法。计算机只懂机器码，高级语言（Python、JS）需要解释器/编译器翻译。",
      points: [
        { title: "程序三要素", text: "输入 → 处理 → 输出；核心控制结构：顺序、分支（if）、循环（for/while）。" },
        { title: "算法", text: "算法的标准：正确、有穷、可执行。排序、查找是最经典算法问题。" },
        { title: "语言怎么跑", text: "编译型（C/Rust）先翻译成机器码；解释型（Python/JS）逐行执行；Web 代码由浏览器解释。" },
      ],
      analogy: "程序像菜谱：食材（数据）、步骤（算法）、语言（菜谱文字）。老厨师（编译器）把菜谱变成动作；步骤错了，菜就做砸了。",
      summary: ["程序由数据、指令与流程控制组成。", "算法是解决问题的明确步骤。", "高级语言经编译或解释后执行。"],
      mistakes: ["以为编程就是背语法。", "跳过算法直接抄代码。", "混淆编译型和解释型语言。"],
      thinking: ["为什么说「程序 = 数据结构 + 算法」？", "bug 一词怎么来的？"],
      exercises: ["写一份「煮泡面」算法，要求别人能照做。", "找出现实中一个 if 分支的例子并描述。"],
      quiz: [
        singleChoice("q1", "程序的核心流程控制包括？", ["顺序、分支、循环", "颜色、字体、排版", "开机、关机、重启", "输入输出颜色"], 0, "三种基本结构。"),
        trueFalse("q2", "算法必须能在有限步骤内结束。", true, "有穷性是算法标准。"),
        fillBlank("q3", "Python 属于____型语言。", "解释", "逐行解释执行。"),
      ],
      tags: ["程序", "算法", "编程"],
      simulator: "python",
      draft: true,
    }),
    quickLesson({
      slug: "setup-env",
      title: "开发环境",
      subtitle: "Python 安装与 VS Code",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["安装 Python", "配置 VS Code", "运行第一个程序"],
      overview: "开发环境三件套：Python 解释器、代码编辑器（VS Code）、终端。安装时勾选「Add Python to PATH」，VS Code 装 Python 扩展，终端运行 python 命令验证。",
      points: [
        { title: "安装 Python", text: "官网 python.org 下载稳定版；安装时勾选 Add Python to PATH；终端输入 python --version 验证。" },
        { title: "VS Code", text: "code.visualstudio.com 下载；安装 Python、Chinese Language Pack、Code Runner 扩展。" },
        { title: "第一个程序", text: "新建 hello.py，写 print(\"你好，电脑学院\")，点击运行或终端 python hello.py。" },
      ],
      analogy: "装开发环境像开餐厅前备厨房：Python 是灶台（解释器），VS Code 是菜板（编辑器），终端是传菜窗口（运行）。",
      summary: ["Python 安装勾选 PATH，终端验证。", "VS Code 装 Python 扩展。", "第一个程序 print 输出。"],
      mistakes: ["安装时不勾 PATH，运行 python 报错。", "装了多个 Python 版本，环境混乱。", "把代码文件命名为 python.py 导致导入冲突。"],
      thinking: ["PATH 是什么？为什么勾选它？", "解释器和编译器的区别？"],
      exercises: ["安装 Python 和 VS Code，验证版本。", "运行你的第一个 print 程序并截图。"],
      quiz: [
        singleChoice("q1", "验证 Python 安装的命令是？", ["python --version", "python start", "run python", "check python"], 0, "--version 验证。"),
        trueFalse("q2", "安装 Python 时应勾选 Add Python to PATH。", true, "便于命令行调用。"),
        fillBlank("q3", "VS Code 是____公司推出的免费编辑器。", "微软", "Microsoft。"),
      ],
      tags: ["Python", "环境", "VS Code"],
      draft: true,
    }),
    quickLesson({
      slug: "python-basics",
      title: "Python 基础",
      subtitle: "变量、类型与输入输出",
      durationMinutes: 40,
      difficulty: "入门",
      goals: ["使用变量与基础类型", "掌握输入输出", "写出第一个计算程序"],
      overview: "Python 用变量存数据：整数 int、浮点 float、字符串 str、布尔 bool。input() 接收输入（返回字符串），print() 输出；类型转换 int()/float()/str() 很常用。",
      points: [
        { title: "变量", text: "name = \"小明\"；age = 18。Python 动态类型，但命名要清晰：student_name 比 s 好。" },
        { title: "输入输出", text: "name = input(\"你的名字：\")；print(\"你好\", name)；input 返回字符串，算数要转 int()。" },
        { title: "f-string", text: "print(f\"我是{name}，今年{age}岁\") 是格式化输出的现代写法。" },
      ],
      analogy: "变量像带标签的盒子：盒子上写名字（变量名），里面装数据。盒子可以换内容，但标签要让人看得懂。",
      summary: ["变量命名清晰，动态类型。", "input 返回字符串，需类型转换。", "f-string 让输出简洁。"],
      mistakes: ["input 后直接做加法，字符串拼接报错。", "变量名用中文/关键字。", "缩进不一致导致语法错误。"],
      thinking: ["为什么 input 返回字符串？", "动态类型有什么好处和坏处？"],
      exercises: ["写程序：询问姓名和年龄，输出「你好，XX，明年 XX 岁」。", "写一个计算两个数平均值的程序。"],
      quiz: [
        singleChoice("q1", "input() 返回的数据类型是？", ["字符串", "整数", "浮点", "布尔"], 0, "input 总是返回字符串。"),
        trueFalse("q2", "Python 变量必须先声明类型。", false, "动态类型。"),
        fillBlank("q3", "格式化字符串前缀是 f，写法 f\"{____}\"。", "变量", "f-string。"),
      ],
      tags: ["Python", "变量", "入门"],
      simulator: "python",
      draft: true,
    }),
    quickLesson({
      slug: "python-logic",
      title: "Python 逻辑",
      subtitle: "if、for、while 与列表",
      durationMinutes: 40,
      difficulty: "入门",
      goals: ["使用条件判断", "掌握循环", "操作列表"],
      overview: "逻辑控制是程序的灵魂：if/elif/else 判断，for 遍历，while 条件循环，list 存序列数据。range() 生成数字序列，len() 取长度。",
      points: [
        { title: "if 判断", text: "if score >= 60: print(\"及格\")。缩进决定代码块，比较用 ==、!=、>=。" },
        { title: "循环", text: "for i in range(5) 循环 5 次；for name in names 遍历列表；while 适合不确定次数。" },
        { title: "列表", text: "scores = [88, 92, 76]；追加 append()，索引从 0 开始，切片 scores[1:3]。" },
      ],
      analogy: "if 像岔路口的选择，for 像按名单点名，while 像「直到水开才关火」。程序就是这些选择与重复的组合。",
      summary: ["if/elif/else 处理分支。", "for 遍历，while 条件循环。", "列表是有序可变的序列。"],
      mistakes: ["忘记冒号或缩进。", "用 = 比较而写成 ==。", "循环条件写错导致死循环。"],
      thinking: ["range(1, 6) 包含哪些数？", "for 和 while 什么时候互相替代？"],
      exercises: ["写程序判断成绩等级（90/75/60 分档）。", "用 for 循环求 1 到 100 的和。"],
      quiz: [
        singleChoice("q1", "Python 判断语句用哪个关键字？", ["if", "when", "case", "do"], 0, "if 判断。"),
        singleChoice("q2", "range(3) 生成的序列是？", ["0,1,2", "1,2,3", "3", "0,1,2,3"], 0, "从 0 开始。"),
        trueFalse("q3", "缩进在 Python 中决定代码块。", true, "缩进即语法。"),
      ],
      tags: ["Python", "逻辑", "循环"],
      simulator: "python",
      draft: true,
    }),
    quickLesson({
      slug: "python-functions",
      title: "Python 函数",
      subtitle: "复用代码的艺术",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["定义与调用函数", "理解参数与返回值", "使用内置函数"],
      overview: "函数是命名并打包的一段代码：def 函数名(参数): ... return 结果。函数让代码复用、测试和阅读都更简单。",
      points: [
        { title: "定义函数", text: "def add(a, b): return a + b。参数是输入，return 是输出；没有 return 返回 None。" },
        { title: "默认参数", text: "def greet(name, lang=\"zh\")：lang 有默认值，调用时可省略。" },
        { title: "内置函数", text: "len()、sum()、max()、min()、sorted()、type() 是高频内置函数。" },
      ],
      analogy: "函数像菜谱上的「备用做法」：写好一次（定义），以后随时喊名字调用。参数是备料，return 是出锅的菜。",
      summary: ["def 定义，return 返回。", "参数让函数通用，默认参数更灵活。", "善用内置函数减少重复造轮子。"],
      mistakes: ["定义函数后忘记调用。", "return 写在循环里提前结束。", "参数名和全局变量混淆。"],
      thinking: ["函数参数传递是值还是引用？", "为什么要有 return？"],
      exercises: ["写一个计算圆面积的函数。", "把之前求和的代码封装成函数，传入任意 n。"],
      quiz: [
        singleChoice("q1", "Python 定义函数的关键字是？", ["def", "func", "function", "define"], 0, "def 定义。"),
        trueFalse("q2", "没有 return 的函数返回 None。", true, "默认返回 None。"),
        fillBlank("q3", "函数把计算结果交还调用方的关键字是____。", "return", "返回值。"),
      ],
      tags: ["Python", "函数", "复用"],
      simulator: "python",
      draft: true,
    }),
    quickLesson({
      slug: "debugging",
      title: "调试",
      subtitle: "读报错、print 与断点",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["读懂 Python 报错", "使用 print 调试", "使用 VS Code 断点"],
      overview: "调试是编程日常：先读错误信息最后一行（错误类型和位置），再用 print 输出中间值，最后用 VS Code 断点单步执行。报错不可怕，可怕的是不看报错。",
      points: [
        { title: "读报错", text: "Traceback 最后一行是错误类型：NameError 未定义、TypeError 类型错误、IndexError 越界、SyntaxError 语法错。" },
        { title: "print 调试", text: "在关键步骤 print 变量，缩小问题范围；调试完记得删除或注释。" },
        { title: "断点", text: "VS Code 点击行号设断点，F5 调试，逐行看变量变化。" },
      ],
      analogy: "报错像 GPS 导航：它告诉你「前方路口转错」（错误位置），你要做的是看路牌（报错信息），而不是问为什么没导航到。",
      summary: ["错误类型与位置在报错最后一行。", "print 中间值是快速定位手段。", "断点单步适合复杂逻辑。"],
      mistakes: ["报错截图发给 AI 却不看自己代码。", "报错后随机乱改代码。", "调试代码不清理，留在作业里。"],
      thinking: ["为什么「讲给橡皮鸭听」能解决调试问题？", "异常处理 try/except 何时使用？"],
      exercises: ["故意制造 NameError 和 IndexError，读报错并修复。", "用 print 调试一个计算结果错误的程序。"],
      quiz: [
        singleChoice("q1", "列表越界会抛什么错误？", ["IndexError", "NameError", "SyntaxError", "KeyError"], 0, "IndexError 索引越界。"),
        trueFalse("q2", "报错信息最后一行最值得先读。", true, "错误类型与位置。"),
        fillBlank("q3", "VS Code 中在行号旁点击可设置____。", "断点", "Breakpoint。"),
      ],
      tags: ["调试", "报错", "Python"],
      simulator: "python",
      draft: true,
    }),
    quickLesson({
      slug: "html",
      title: "HTML",
      subtitle: "网页的骨架",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["理解 HTML 结构", "使用常用标签", "创建第一个网页"],
      overview: "HTML 描述网页内容结构：<!DOCTYPE html> 声明、<html> 根、<head> 元信息、<body> 可见内容。标签成对出现，如 <h1>标题</h1>、<p>段落</p>、<a>链接</a>。",
      points: [
        { title: "文档结构", text: "html > head + body；head 里放 title、meta，body 放页面内容。" },
        { title: "常用标签", text: "h1-h6 标题、p 段落、a 链接、img 图片、ul/li 列表、div 容器、span 行内。" },
        { title: "属性", text: "a 的 href 指向链接，img 的 src 指向图片，class/id 用于样式定位。" },
      ],
      analogy: "HTML 像毛坯房的骨架：墙体（div）、房间门（a）、窗户（img）各有位置；CSS 是装修，JavaScript 是水电智能。",
      summary: ["HTML 是内容结构语言。", "标签成对，属性补充信息。", "head 与 body 分工明确。"],
      mistakes: ["忘记闭合标签。", "用 div 包一切不注重语义。", "图片不写 alt 影响可访问性。"],
      thinking: ["语义化标签（header/main/footer）为什么重要？", "HTML 是编程语言吗？"],
      exercises: ["写一个包含标题、段落、链接、列表、图片的自我介绍网页。", "用浏览器开发者工具查看一个网站的 HTML 结构。"],
      quiz: [
        singleChoice("q1", "段落标签是？", ["<p>", "<h1>", "<div>", "<a>"], 0, "p 是段落。"),
        singleChoice("q2", "链接标签的地址属性是？", ["href", "src", "alt", "class"], 0, "href 链接地址。"),
        trueFalse("q3", "HTML 标签通常成对出现。", true, "开始与结束标签。"),
      ],
      tags: ["HTML", "网页", "入门"],
      simulator: "html",
      draft: true,
    }),
    quickLesson({
      slug: "css",
      title: "CSS",
      subtitle: "网页的美化与布局",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["理解 CSS 语法", "掌握选择器", "实现基础布局"],
      overview: "CSS 负责样式：选择器（元素/class/id）+ 声明（属性: 值）。布局用 Flexbox 或 Grid，响应式用媒体查询。CSS 决定网页好不好看。",
      points: [
        { title: "选择器", text: "p 选所有段落；.card 选 class；#header 选 id；后代选择器 .nav a。优先级 class > 元素。" },
        { title: "盒模型", text: "每个元素是盒子：content + padding + border + margin。box-sizing: border-box 让宽度计算更直观。" },
        { title: "布局", text: "display: flex 一行排列；gap 间距；justify-content 主轴对齐；grid 适合网格布局。" },
      ],
      analogy: "CSS 像室内装修：选择器是「给哪间房刷漆」，声明是「刷什么颜色」，Flexbox 是「家具怎么摆」。",
      summary: ["选择器 + 声明构成 CSS。", "盒模型是布局基础。", "Flexbox 是当前最常用布局方式。"],
      mistakes: ["不理解优先级，样式不生效。", "忘记 box-sizing 导致布局错乱。", "所有布局都用 position 硬调。"],
      thinking: ["为什么推荐 Flexbox 而不是 float？", "CSS 的层叠是什么意思？"],
      exercises: ["给自我介绍网页加背景色、字体和卡片样式。", "用 Flexbox 做一个 3 列卡片布局。"],
      quiz: [
        singleChoice("q1", "class 选择器的写法是？", [".card", "#card", "card", "@card"], 0, "点号加类名。"),
        singleChoice("q2", "元素内容与边框之间的空间是？", ["padding", "margin", "border", "gap"], 0, "padding 内边距。"),
        trueFalse("q3", "Flexbox 用于一维布局，Grid 适合二维。", true, "各有所长。"),
      ],
      tags: ["CSS", "样式", "布局"],
      simulator: "html",
      draft: true,
    }),
    quickLesson({
      slug: "javascript",
      title: "JavaScript",
      subtitle: "网页的交互大脑",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["理解 JS 作用", "使用变量与函数", "处理点击事件"],
      overview: "JavaScript 让网页可交互：点击按钮、表单验证、数据请求。const 声明变量、函数 function、事件 addEventListener。现代 JS 运行在浏览器和 Node.js。",
      points: [
        { title: "基础语法", text: "const 常量、let 变量；函数 function greet(name) {}；模板字符串 `Hello ${name}`。" },
        { title: "DOM 操作", text: "document.querySelector('.btn') 选元素；textContent 改文字；classList 切换样式。" },
        { title: "事件", text: "btn.addEventListener('click', () => { ... })；事件让页面活起来。" },
      ],
      analogy: "JS 像水电智能系统：HTML 是墙（结构），CSS 是漆（外观），JS 是开关和电路（行为）。按开关（点击），灯才亮（响应）。",
      summary: ["JS 负责网页行为交互。", "DOM 选择与事件监听是基础。", "现代前端框架都构建在 JS 上。"],
      mistakes: ["script 标签放 head 里导致找不到元素。", "用 == 比较忽略类型差异。", "操作不存在的元素直接报错。"],
      thinking: ["const 和 let 的区别？", "前端框架为什么出现？"],
      exercises: ["给网页加一个按钮，点击改变文字。", "写一个 JS 函数计算两数之和并显示结果。"],
      quiz: [
        singleChoice("q1", "JS 中声明常量的关键字是？", ["const", "static", "final", "fixed"], 0, "const 声明常量。"),
        singleChoice("q2", "监听点击事件的方法是？", ["addEventListener", "onClickSet", "listenClick", "clickMe"], 0, "addEventListener。"),
        trueFalse("q3", "JavaScript 可以直接在浏览器运行。", true, "浏览器内置引擎。"),
      ],
      tags: ["JavaScript", "交互", "网页"],
      simulator: "html",
      draft: true,
    }),
    quickLesson({
      slug: "git",
      title: "Git",
      subtitle: "版本控制的时光机",
      durationMinutes: 35,
      difficulty: "进阶",
      goals: ["理解 Git 工作区", "掌握 add/commit", "使用分支"],
      overview: "Git 是分布式版本控制系统：每次 commit 是快照，随时回退；branch 是平行开发线；remote 是远程仓库。学 Git 先学三件事：add 暂存、commit 提交、log 查看。",
      points: [
        { title: "核心命令", text: "git init 初始化；git add . 暂存；git commit -m \"消息\" 提交；git status 查看状态；git log 查看历史。" },
        { title: "撤销", text: "git restore 文件 丢弃工作区修改；git reset --soft HEAD~1 撤销提交保留修改（小心使用）。" },
        { title: "分支", text: "git branch 新分支；git checkout 切换；git merge 合并。分支让实验代码不破坏主线。" },
      ],
      analogy: "Git 像游戏存档：commit 是存档点，branch 是平行世界，merge 是把平行世界合并回主世界，reset 是读档重来（小心丢进度）。",
      summary: ["Git 记录文件快照与历史。", "add → commit 是核心循环。", "分支让多线开发安全。"],
      mistakes: ["提交信息乱写，历史不可读。", "把密钥和 node_modules 提交进仓库。", "在未提交时直接删文件，无法恢复。"],
      thinking: ["Git 和云盘同步的本质区别？", "为什么提交信息要规范？"],
      exercises: ["在练习目录初始化 Git，完成 3 次提交。", "创建一个分支修改文件后合并回主分支。"],
      quiz: [
        singleChoice("q1", "暂存修改的命令是？", ["git add", "git save", "git push", "git load"], 0, "add 暂存。"),
        trueFalse("q2", "commit 之后仍可查看历史。", true, "log 查看。"),
        fillBlank("q3", "查看提交历史的命令是 git ____。", "log", "git log。"),
      ],
      tags: ["Git", "版本控制", "工具"],
      draft: true,
    }),
    quickLesson({
      slug: "github",
      title: "GitHub",
      subtitle: "代码的家与开源社区",
      durationMinutes: 35,
      difficulty: "进阶",
      goals: ["创建 GitHub 仓库", "掌握 push/pull", "理解开源协作"],
      overview: "GitHub 是 Git 的云端家园：remote add origin 关联、git push 上传、git pull 拉取。GitHub 也是最大开源社区：README、Issue、Pull Request、Actions 都是协作基建。",
      points: [
        { title: "推送流程", text: "git remote add origin 地址；git push -u origin main；之后 git push 即可。" },
        { title: "协作", text: "fork 复制别人的仓库 → clone 到本地 → 改 → pull request 提交合并请求。" },
        { title: "GitHub Actions", text: "仓库里的 CI/CD：push 后自动测试、构建、部署；.github/workflows 配置。" },
      ],
      analogy: "GitHub 像代码界的图书馆：Git 是你的手稿，GitHub 是图书馆书架，PR 是投稿审稿，Actions 是自动装订机。",
      summary: ["remote + push/pull 是远程协作基础。", "fork + PR 是开源贡献流程。", "Actions 自动化测试部署。"],
      mistakes: ["把密码写进代码再 push。", "忘记 git pull 直接 push 导致冲突。", "clone 别人的项目改完乱提 PR。"],
      thinking: ["开源协议（MIT/GPL）有什么区别？", "为什么团队用 PR 而不是直接推 main？"],
      exercises: ["创建第一个 GitHub 仓库并推送你的练习项目。", "给任意开源项目提交一个 README 翻译或文档修正 PR。"],
      quiz: [
        singleChoice("q1", "把本地提交上传到远程的命令是？", ["git push", "git pull", "git clone", "git fetch"], 0, "push 上传。"),
        singleChoice("q2", "参与开源项目提修改请求的方式是？", ["Pull Request", "邮件附件", "微信群发", "U 盘拷贝"], 0, "PR 是标准流程。"),
        trueFalse("q3", "GitHub Actions 可以自动运行测试。", true, "CI/CD 自动化。"),
      ],
      tags: ["GitHub", "开源", "协作"],
      draft: true,
    }),
    quickLesson({
      slug: "mini-project",
      title: "综合小项目",
      subtitle: "把知识串成作品",
      durationMinutes: 45,
      difficulty: "进阶",
      goals: ["设计一个小项目", "综合运用所学", "发布作品"],
      overview: "学编程最好的验证是作品：做一个「课程笔记管理网页」或「成绩计算器」，把 HTML/CSS/JS/Python/Git 串起来，然后推到 GitHub。",
      points: [
        { title: "选题", text: "从 20 分钟能做完的最小版本开始：待办清单、名片页、BMI 计算器。先做完再做漂亮。" },
        { title: "流程", text: "需求一句话 → 界面草图 → 数据/逻辑 → 美化 → 测试 → Git 提交 → GitHub 发布。" },
        { title: "发布", text: "GitHub Pages 可免费部署静态网页；README 写清项目用途与运行方式。" },
      ],
      analogy: "小项目像毕业设计前的练习：不是给老师看，而是给自己证明「我能从零到一」。完成比完美重要。",
      summary: ["最小可用版本优先。", "完整流程：需求 → 开发 → 测试 → 发布。", "GitHub 就是你的作品集。"],
      mistakes: ["项目越做越大，永远完不成。", "只抄教程不改需求，失去练习意义。", "写代码不提交，作品丢失。"],
      thinking: ["如何拆解一个大项目为小任务？", "README 应该写什么？"],
      exercises: ["完成一个最小待办清单网页，部署到 GitHub Pages。", "写一份项目 README 并提交。"],
      quiz: [
        singleChoice("q1", "小项目开发的第一步是？", ["明确需求", "买服务器", "写 1000 行代码", "注册商标"], 0, "需求先行。"),
        trueFalse("q2", "GitHub Pages 可以免费部署静态网页。", true, "免费静态托管。"),
        fillBlank("q3", "代码仓库的介绍文档通常命名为____。", "README", "README.md。"),
      ],
      tags: ["项目", "作品", "综合"],
      simulator: "html",
      draft: true,
    }),
  ],
};
