import { CourseModule } from "@/lib/schema";
import {
  fillBlank,
  moduleMeta,
  quickLesson,
  singleChoice,
  trueFalse,
} from "@/content/helpers";

export const module12: CourseModule = {
  ...moduleMeta({
    slug: "12-future",
    order: 12,
    title: "未来发展路线",
    subtitle: "从会用电脑到会选方向",
    description: "程序员、设计、AI、网络安全、数据分析，找到属于自己的数字职业路线。",
    icon: "Compass",
    accent: "from-slate-500 to-zinc-400",
    difficulty: "基础",
    estimatedMinutes: 280,
    draft: true,
  }),
  lessons: [
    quickLesson({
      slug: "career-map",
      title: "数字职业地图",
      subtitle: "了解行业全景",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["了解数字职业大类", "理解岗位与技能关系", "建立探索心态"],
      overview: "数字职业不是只有程序员：产品、设计、数据、安全、运营、AI 各有天地。选择方向的关键是「兴趣 × 能力 × 市场」，大学四年是试错期。",
      points: [
        { title: "六大方向", text: "开发、设计、数据、安全、AI、产品运营。每个方向下又有细分岗位。" },
        { title: "技能组合", text: "单一技能容易被替代，组合技能更值钱：编程+业务、设计+AI、数据+领域知识。" },
        { title: "信息获取", text: "看招聘网站的岗位要求、访谈行业前辈、参加校园技术社团；少看焦虑贩卖，多看一手 JD。" },
      ],
      analogy: "职业地图像自助餐厅：先逛一圈（了解岗位），再尝小份（实习/项目），最后决定主菜（方向）。不用第一天就锁定。",
      summary: ["数字职业六大方向各有路径。", "组合技能更有竞争力。", "招聘要求是一手情报。"],
      mistakes: ["跟风热门专业不评估自己。", "只看薪资不看岗位要求。", "大学四年不实践，毕业才迷茫。"],
      thinking: ["「会用 AI 的人」如何影响各岗位？", "什么技能是十年后仍值钱的？"],
      exercises: ["浏览 3 个岗位 JD，整理所需技能清单。", "列出你感兴趣的方向，各找一位可访谈的前辈。"],
      quiz: [
        singleChoice("q1", "了解岗位需求最一手的信息源是？", ["招聘 JD", "营销号", "贴吧", "亲戚传言"], 0, "JD 是真实要求。"),
        trueFalse("q2", "单一技能比组合技能更有竞争力。", false, "组合技能更稀缺。"),
        fillBlank("q3", "把兴趣、能力和市场需求结合的选择叫____匹配。", "人岗", "人岗匹配。"),
      ],
      tags: ["职业", "地图", "方向"],
      draft: true,
    }),
    quickLesson({
      slug: "programmer",
      title: "程序员",
      subtitle: "前端、后端、全栈与算法",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["了解程序员细分", "理解学习路径", "规划第一年行动"],
      overview: "程序员方向：前端（界面交互）、后端（服务数据）、全栈（两者）、算法（模型推理）、移动/游戏等。入门推荐「HTML/CSS/JS → Python → 数据库 → 一个框架 → 项目」。",
      points: [
        { title: "细分岗位", text: "前端 React/Vue；后端 Java/Go/Node；数据工程师 SQL/Python；算法工程师数学+模型。" },
        { title: "学习路径", text: "基础语法 → 数据结构 → Web → 数据库 → 框架 → 项目 → 开源贡献/实习。" },
        { title: "软技能", text: "读英文文档、Git 协作、写注释、提问能力、代码审美；编程是长期积累。" },
      ],
      analogy: "程序员像建造师：前端是外观设计，后端是水电结构，数据库是仓库管理，算法是智能规划。懂全流程才能当好包工头（架构师）。",
      summary: ["程序员分前端、后端、数据、算法等方向。", "项目实践是学习路径的核心。", "英文文档与协作能力决定上限。"],
      mistakes: ["只刷题不写项目。", "Java 学一个月换 Python 再换 Go。", "不看英文文档，永远落后一手资料。"],
      thinking: ["为什么说编程是「低门槛高天花板」？", "AI 会取代程序员吗？"],
      exercises: ["给自己规划 12 个月编程学习路线图。", "参与一次校内 Hackathon 或开源贡献。"],
      quiz: [
        singleChoice("q1", "负责界面交互的开发方向是？", ["前端", "后端", "运维", "DBA"], 0, "前端面向界面。"),
        trueFalse("q2", "项目实践比只刷题更重要。", true, "作品证明能力。"),
        fillBlank("q3", "React 和 Vue 属于____端框架。", "前", "前端框架。"),
      ],
      tags: ["程序员", "开发", "路线"],
      draft: true,
    }),
    quickLesson({
      slug: "design",
      title: "设计",
      subtitle: "UI、UX 与视觉",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["了解设计岗位细分", "理解设计思维", "建立作品集意识"],
      overview: "设计方向：UI 视觉、UX 体验、品牌、插画、动效。核心不是软件技巧而是「理解用户与解决问题」；Figma、Adobe 是工具，作品集是敲门砖。",
      points: [
        { title: "UI 与 UX", text: "UI 管好不好看，UX 管好不好用；二者常合并。方法论：用户调研 → 信息架构 → 线框图 → 高保真 → 测试。" },
        { title: "工具", text: "Figma（协作设计）、Photoshop/Illustrator（视觉）、即时设计（国内）；AI 生成图可辅助灵感但慎用于交付。" },
        { title: "作品集", text: "每个项目讲清问题、方案、结果；Redesign 练习也可以；作品集持续更新胜过一次性精修。" },
      ],
      analogy: "设计师像餐厅菜单设计师：好看（UI）让人想点，好用（UX）让人点得顺。菜单再美，找不到菜名也失败。",
      summary: ["设计是解决问题，不是美化装饰。", "Figma 是协作设计主流工具。", "作品集记录思考过程比成品重要。"],
      mistakes: ["只会套模板，说不出设计理由。", "作品集只放最终图不放过程。", "忽视竞品分析和用户测试。"],
      thinking: ["AI 生成图对设计师是威胁还是工具？", "好设计和好艺术的区别？"],
      exercises: ["用 Figma 重设计一个 App 首页并写设计说明。", "找 3 个界面做竞品分析，列出各自优劣。"],
      quiz: [
        singleChoice("q1", "UX 关注的核心是？", ["好不好用", "好不好看", "快不快", "贵不贵"], 0, "体验可用性。"),
        trueFalse("q2", "作品集只需要放最终成品图。", false, "过程同样重要。"),
        fillBlank("q3", "设计师协作设计的主流工具是____。", "Figma", "Figma。"),
      ],
      tags: ["设计", "UI", "UX"],
      draft: true,
    }),
    quickLesson({
      slug: "ai-career",
      title: "AI 方向",
      subtitle: "应用、开发与研究",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["了解 AI 岗位层级", "区分应用与研发", "规划学习路径"],
      overview: "AI 职业分三层：应用层（Prompt 工程、AI 产品、Agent 开发）、工程层（模型微调、RAG、部署）、研究层（预训练、算法）。本科从应用和工程切入更现实。",
      points: [
        { title: "应用层", text: "会用 LLM API、搭 RAG 知识库、写 Agent 工作流；门槛是编程基础 + 业务理解。" },
        { title: "工程层", text: "PyTorch 微调、向量数据库、模型推理优化；需要扎实 Python、机器学习基础。" },
        { title: "研究层", text: "读论文、复现模型、发表工作；通常需要硕博与数学功底。" },
      ],
      analogy: "AI 岗位像汽车行业：应用层是司机（会用）、工程层是修车师傅（会改）、研究层是造发动机（会研）。会开车比会造发动机先上路。",
      summary: ["AI 职业分应用、工程、研究三层。", "应用与工程是本科更现实的切入点。", "数学、Python、业务理解是共同底座。"],
      mistakes: ["一上来读论文不做项目。", "以为会 ChatGPT 就是 AI 人才。", "忽视数学基础，卡在工程层。"],
      thinking: ["Agent 和普通聊天机器人的区别？", "RAG 为什么成为企业 AI 标配？"],
      exercises: ["用 LLM API 搭一个 100 行以内的问答助手。", "调研 3 个 AI 岗位 JD，标注共同技能。"],
      quiz: [
        singleChoice("q1", "RAG 的核心作用是？", ["给模型外挂知识库", "加速显卡", "美化界面", "压缩模型"], 0, "检索增强生成。"),
        trueFalse("q2", "会使用 ChatGPT 就等于 AI 工程师。", false, "研发能力才够。"),
        fillBlank("q3", "AI 应用开发常用 Python 框架____。", "PyTorch", "PyTorch 等。"),
      ],
      tags: ["AI", "职业", "路线"],
      draft: true,
    }),
    quickLesson({
      slug: "security",
      title: "网络安全",
      subtitle: "白帽、渗透与防御",
      durationMinutes: 35,
      difficulty: "进阶",
      goals: ["了解安全岗位", "理解攻击与防御", "遵守安全伦理"],
      overview: "网络安全岗位：渗透测试（找漏洞）、安全运维（防漏洞）、安全研发（修漏洞）、应急响应（处理事件）。入行从 CTF 竞赛和合法靶场开始，红线是不碰未授权系统。",
      points: [
        { title: "核心知识", text: "网络协议（TCP/IP）、操作系统、Web 漏洞（SQL 注入、XSS）、加密基础；工具如 Burp Suite、nmap。" },
        { title: "学习路径", text: "Linux → 网络 → Web 基础 → CTF 刷题（picoCTF 等）→ 漏洞靶场（DVWA）→ 实习。" },
        { title: "伦理红线", text: "只测有授权的系统；渗透测试要签协议；未授权测试违法，别拿「学习」当挡箭牌。" },
      ],
      analogy: "白帽黑客像门锁测试员：拿钥匙清单（工具）挨个试（测试），但只测客户授权的门（授权范围）。自己乱撬门就是小偷。",
      summary: ["安全岗位覆盖攻防研应。", "CTF 与靶场是合法入门路径。", "未经授权测试是违法犯罪。"],
      mistakes: ["拿同学网站练手被报警。", "只看黑客教程不学网络基础。", "把扫描工具当万能钥匙。"],
      thinking: ["为什么安全人才缺口大？", "「黑客」和「白帽」的区别是什么？"],
      exercises: ["注册 picoCTF 完成前 3 道入门题。", "阅读《网络安全法》中与你相关的条款。"],
      quiz: [
        singleChoice("q1", "未授权渗透测试属于？", ["违法", "合法", "灰色但无责", "道德义务"], 0, "未授权即违法。"),
        singleChoice("q2", "Web 常见漏洞之一是？", ["SQL 注入", "电池损耗", "屏幕老化", "键盘失灵"], 0, "SQL 注入是经典 Web 漏洞。"),
        trueFalse("q3", "CTF 是学习安全的合法途径之一。", true, "竞赛平台授权挑战。"),
      ],
      tags: ["安全", "黑客", "渗透"],
      draft: true,
    }),
    quickLesson({
      slug: "data-analysis",
      title: "数据分析",
      subtitle: "从数据到决策",
      durationMinutes: 35,
      difficulty: "基础",
      goals: ["了解数据分析岗位", "掌握分析流程", "学会用工具讲故事"],
      overview: "数据分析是把业务问题变成数据问题：明确问题 → 取数 → 清洗 → 分析 → 可视化 → 结论建议。工具：Excel → SQL → Python（Pandas）→ 可视化（Tableau/Power BI）。",
      points: [
        { title: "技能栈", text: "SQL 取数、Excel 快分析、Python 深分析、可视化呈现；业务理解让分析有灵魂。" },
        { title: "分析思维", text: "对比、拆解、漏斗、相关性；先问「所以呢」，再问「怎么办」。" },
        { title: "作品", text: "用公开数据集（Kaggle、国家统计局）做完整分析报告，讲清业务问题与结论。" },
      ],
      analogy: "数据分析师像侦探：线索（数据）要采集（SQL）、清洗（去伪）、推理（统计）、画图（证据链）、结案陈词（建议）。",
      summary: ["流程：问题 → 取数 → 清洗 → 分析 → 结论。", "SQL + Python + 可视化是核心栈。", "业务理解决定分析价值。"],
      mistakes: ["先找数据再想问题，分析无的放矢。", "可视化花哨但没有结论。", "把相关当因果。"],
      thinking: ["为什么说「分析报告最后一页才有价值」？", "数据清洗为什么占 70% 时间？"],
      exercises: ["下载一份公开数据集，完成一次完整分析并写成报告。", "用 SQL 练习平台完成 10 道查询题。"],
      quiz: [
        singleChoice("q1", "数据分析第一步是？", ["明确业务问题", "下载数据", "画图", "写报告"], 0, "问题先行。"),
        singleChoice("q2", "数据库取数最常用的语言是？", ["SQL", "HTML", "CSS", "Markdown"], 0, "SQL 查询。"),
        trueFalse("q3", "相关关系不等于因果关系。", true, "统计常识。"),
      ],
      tags: ["数据分析", "SQL", "Python"],
      draft: true,
    }),
    quickLesson({
      slug: "growth-path",
      title: "大学四年成长路线",
      subtitle: "从大一到大四怎么走",
      durationMinutes: 35,
      difficulty: "入门",
      goals: ["制定分年级计划", "平衡学业与技能", "建立作品与网络"],
      overview: "通用成长节奏：大一打基础（课程+习惯）、大二选方向（技能+社团）、大三做作品（项目+实习）、大四收成果（简历+校招）。方向可以调，节奏别停。",
      points: [
        { title: "大一", text: "学好公共课，掌握电脑基础（本课程），尝试 3 个方向，养成笔记与时间管理习惯。" },
        { title: "大二", text: "确定主方向，系统学技能，参加比赛/社团，完成 1-2 个小项目。" },
        { title: "大三", text: "深度项目 + 实习，建立作品集/GitHub，关注校招要求，简历迭代。" },
      ],
      analogy: "大学四年像开荒种地：大一翻土（基础），大二播种（方向），大三浇水施肥（项目实习），大四收成（offer）。翻土太浅，后面白忙。",
      summary: ["大一探索、大二定向、大三深耕、大四收获。", "作品与实习是简历核心。", "方向可调整，习惯不能断。"],
      mistakes: ["大一躺平，大三焦虑。", "只上课不实践，简历空白。", "频繁换方向，每样只学了皮毛。"],
      thinking: ["绩点和技能哪个更重要？", "如何利用寒暑假积累作品？"],
      exercises: ["按你现在年级制定一份半年行动计划。", "把「想做的事」拆成每周 3 小时可执行任务。"],
      quiz: [
        singleChoice("q1", "大二阶段最该做的是？", ["确定方向并系统学习", "只刷绩点", "躺平", "直接海投简历"], 0, "定向学习。"),
        trueFalse("q2", "作品和实习比简历模板更重要。", true, "内容为王。"),
        fillBlank("q3", "积累项目与开源贡献的平台之一是____。", "GitHub", "GitHub。"),
      ],
      tags: ["大学", "成长", "规划"],
      draft: true,
    }),
    quickLesson({
      slug: "ai-plus-career",
      title: "AI + 你的专业",
      subtitle: "复合能力的时代",
      durationMinutes: 30,
      difficulty: "入门",
      goals: ["理解 AI 对各行业影响", "找到本专业的 AI 结合点", "建立终身学习习惯"],
      overview: "未来竞争力不是「会不会 AI」，而是「AI × 专业」：法律+AI、医学+AI、教育+AI、会计+AI。每个专业都值得学会用 AI 放大自己的专业能力。",
      points: [
        { title: "行业结合", text: "法律文书审查、医学影像辅助、教育个性化、财务自动化；AI 是放大器，专业是地基。" },
        { title: "终身学习", text: "技术半年一变，学习能力是唯一护城河；订阅一手信息源，保持动手实践。" },
        { title: "不可替代", text: "判断力、沟通、创造力、责任感是 AI 难替代的；把它们当核心资产培养。" },
      ],
      analogy: "AI 像电力：电气化时代每个行业都用上了电，但懂电的行业专家才能造出更好的产品。AI 时代也一样，会用 AI 的专业人才是赢家。",
      summary: ["「AI × 专业」是复合竞争力。", "学习能力是唯一护城河。", "判断与创造难以替代。"],
      mistakes: ["认为 AI 会取代所有岗位，放弃专业。", "只学 AI 技巧不练专业功底。", "毕业就停止学习。"],
      thinking: ["你的专业里，哪些任务适合 AI 做？", "如何保持「不断更新」而不焦虑？"],
      exercises: ["写出你专业的 5 个 AI 应用场景。", "建立自己的信息源清单：3 个高质量订阅。"],
      quiz: [
        singleChoice("q1", "未来最稀缺的能力组合是？", ["AI × 专业", "只会 AI", "只会专业", "只会办公"], 0, "复合能力。"),
        trueFalse("q2", "终身学习是数字时代的基本生存能力。", true, "技术快速迭代。"),
        fillBlank("q3", "AI 较难替代的能力包括判断力、创造力和____。", "沟通/责任", "人类核心能力。"),
      ],
      tags: ["AI", "复合", "终身学习"],
      draft: true,
    }),
  ],
};
