import {
  Award,
  BatteryCharging,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Braces,
  Cable,
  CalendarCheck,
  CircuitBoard,
  ClipboardPaste,
  CloudUpload,
  Code2,
  Compass,
  Cpu,
  Download,
  FileArchive,
  FilePen,
  FileText,
  Fingerprint,
  Flame,
  FolderTree,
  Gem,
  Globe,
  GraduationCap,
  HardDrive,
  HardDriveDownload,
  KeyRound,
  Link,
  MemoryStick,
  Milestone,
  Monitor,
  MonitorPlay,
  MonitorSmartphone,
  Network,
  PackageOpen,
  PanelsTopLeft,
  Rocket,
  Search,
  ShieldAlert,
  ShoppingCart,
  Sparkles,
  Table2,
  Trophy,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import { LucideIcon } from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  Award,
  BatteryCharging,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Braces,
  Cable,
  CalendarCheck,
  CircuitBoard,
  ClipboardPaste,
  CloudUpload,
  Code2,
  Compass,
  Cpu,
  Download,
  FileArchive,
  FilePen,
  FileText,
  Fingerprint,
  Flame,
  FolderTree,
  Gem,
  Globe,
  GraduationCap,
  HardDrive,
  HardDriveDownload,
  KeyRound,
  Link,
  MemoryStick,
  Milestone,
  Monitor,
  MonitorPlay,
  MonitorSmartphone,
  Network,
  PackageOpen,
  PanelsTopLeft,
  Rocket,
  Search,
  ShieldAlert,
  ShoppingCart,
  Sparkles,
  Table2,
  Trophy,
  Wifi,
  Window: PanelsTopLeft,
  Wrench,
  Zap,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const IconComp = iconMap[name] ?? BookOpen;
  return <IconComp className={className} />;
}
